### ISSUE TITLE
Feature: multiple backend in the same external secret

### ISSUE THREAD

**Issue by Sytten** [external-secrets/kubernetes-external-secrets#132]
Since the project is expanding, it should be possible to have secrets coming from various places in the same externalsecret. That would break the current YAML though so it's quite a major change.

**Comment by Flydiverny** [comment]
Is there really a use case for this though? I mean is there any case where it would end up being an actual problem to create an additional external secret? Seems like a good way to handle it, I'd expect most uses to stick to the same backend type throughout unless migrating from one secret storage to another.

**Comment by Sytten** [comment]
I don't exactly remember the use case since I don't work at the same company anymore, but I feel you might want some information in SM (databases creds for example to use rotation), but most of the stuff in SSM since you have to pay for it.

**Comment by DWSR** [comment]
This is something we'd be very interested in as we currently use HashiVault and SSM Parameter Store for secrets. Using multiple backends enables an easier transition between secret backends and also enables us to avoid duplicating secrets amongst the various backends.

**Comment by Sytten** [comment]
Not stale

**Comment by Sytten** [comment]
Not stale

**Comment by Flydiverny** [comment]
This will not be added to KES.
Neither has it been included in the CRD spec we came up with for ESO. I think the best thing now would be to make a feature request on the rewrite instead.
