### ISSUE TITLE
Allow option to restart if do not have permission to access secrets

### ISSUE THREAD

**Issue by derrickburns** [external-secrets/kubernetes-external-secrets#136]
If the kiam service is not running, then the external secrets will start without permission to access secrets.

At present, external-secrets will log a message.

If kiam then starts, the external-secrets pods will retain the old, incorrect permissions.

To enable the system to self-correct, please add an option that has the external-secrets service to restart if it does not have permission to access secrets.

**Comment by IngussNeilands** [comment]
+1

**Comment by Flydiverny** [comment]
How would one best approach this?
We now have multiple backends, so for some AWS access isn't relevant.
This could also cause false positive restarts of the service, if someone is actually trying to get external-secrets to fetch a secret it doesn't have access to. How to detect if its the service having the wrong credentials provided vs correct credentials without access?
