### ISSUE TITLE
Feature request for null values from System Manager

### ISSUE THREAD

**Issue by manuel-sanchez** [external-secrets/kubernetes-external-secrets#250]
Hi, this is more of a feature request than a bug. SSM doesn't allow to have null values set, however this null values might be useful on the app side. For our app we ended up creating a script that replaces a given value in SSM with null, in our case if the value equals the name of the variable we set the value as null. We could add something similar here if this feature has enough quorum and we can decide a standard. The code change from what I've seen is limited to the system-manager-backend.js

**Comment by manuel-sanchez** [comment]
Here's a PR for this: https://github.com/godaddy/kubernetes-external-secrets/pull/251

**Comment by Flydiverny** [comment]
This feels a bit weird to me, couldn't this be solved by the user? Eg you have a standard in your team that if an ssm value is set to `THIS_IS_NULL` your application could treat it accordingly.
Setting the value to null based on the key name and value matching seems like it could cause a lot of confusion if you are not aware or expecting this behaviour.

**Comment by manuel-sanchez** [comment]
I know this is a weird solution, and definitely parameter store has this shortcoming (not allowing empty values). It doesn't have to be the name of the variable, it could be when the value is `NULL` or some other value. I can move this to be solved on the app side, but if I'm not the only one dealing with this problem it would be nice to have this CDR handle this use case.

**Comment by manuel-sanchez** [comment]
I know this is a weird solution, and definitely parameter store has this shortcoming (not allowing empty values). It doesn't have to be the name of the variable, it could be when the value is `NULL` or some other value. I can move this to be solved on the app side, but if I'm not the only one dealing with this problem it would be nice to have this CDR handle this use case.
