### ISSUE TITLE
kustomization/secretGenerator support

### ISSUE THREAD

**Issue by icy** [external-secrets/kubernetes-external-secrets#289]
Hi there,

How does our tool support secretGenerator in kustomization? See also https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#secretgenerator . The plugin can add some hash to the original secret name, and it's expected that the controller can suggest an appropriate name. 

Thanks

**Comment by MPV** [comment]
For anyone else coming here, the link mentioned in the description seems to have moved to:
https://kubernetes-sigs.github.io/kustomize/guides/plugins/builtins/#_secretgenerator_
