### ISSUE TITLE
How to use AppRole of Hashi Corp Vault instead of Kubernetes authentication method

### ISSUE THREAD

**Issue by sudarshntn** [external-secrets/kubernetes-external-secrets#294]
I have a Hashi Corp vault as a service available which only supports 
- AppRole 
- GitHub 
In this case I want to use your CRD to connect to the hosted Vault to store secrets and then get them loaded to my Kubernetes cluster.
This service doesn't allow Kubernetes authentication method.
Need help on this support and if you have example for the same.

**Comment by Flydiverny** [comment]
I think currently the code only supports kubernetes authentication. So support for this would need to be added, PR's welcome :)
