### ISSUE TITLE
Expose webhook to trigger refresh of secrets

### ISSUE THREAD

**Issue by cep21** [external-secrets/kubernetes-external-secrets#358]
This is a smaller scoped enhancement of #127.  Rather than full integration with SNS or lambda, simply expose an HTTP endpoint that when hit forces a refresh of all (or a subset (??)) of ExternalSecrets.  It would then be an exercise for the user to create the correct SNS/Lambda (or GCP/Azure equivalent) integrations to hit ExternalSecrets's HTTP endpoint when a value is changed.

**Comment by ChapChap** [comment]
Up ! Any update on this ? More globally, how do you guys manually trigger refresh ?

**Comment by Morriz** [comment]
Yeah, event driven refresh should be default in todays async world imo. Periodic sync is costly.
