### ISSUE TITLE
Bump apiextensions version to v1

### ISSUE THREAD

**Issue by andpozo** [external-secrets/kubernetes-external-secrets#377]
Hi folks!

I see that your `CustomResourceDefinition` is based on an old kubernetes api `apiextensions.k8s.io/v1beta1`, I think that the last version with support for this api is 1.16.x, if so, do you plan to migrate the CRD to the new api `apiextensions.k8s.io/v1`?

Thanks in advance.

**Comment by Flydiverny** [comment]
I don't think we can switch to `apiextensions.k8s.io/v1` just yet as that would break any usage for clusters pre 1.16.x.

AFAIK `apiextensions.k8s.io/v1beta1` is not removed yet and will probably be removed first in 1.22 (https://github.com/kubernetes/kubernetes/issues/82022)
