### ISSUE TITLE
Add support for 1password

### ISSUE THREAD

**Issue by omerlh** [external-secrets/kubernetes-external-secrets#378]
Allow users to retrieve secrets stored in 1password vault using 1password API.

**Comment by onedr0p** [comment]
I came here wondering if someone requested this, yes, this would be great!

**Comment by onedr0p** [comment]
I've started looking into this and a couple gotchas for if the maintainers wanted to add support for this.

* From my tests, the op-cli tool doesn't work in alpine, it needs glibc.
* There is no well maintained npm package that wraps op-cli.

**Comment by onedr0p** [comment]
@Flydiverny I saw you thumb up this, would you be open for PRs using the method I describe above by switch from `alpine` to `slim` and wrapping the cli tool?

**Comment by Flydiverny** [comment]
@onedr0p PR's for sure welcome for this! I think switching to `slim` would be fine and wrapping the cli tool works, maybe not ideal but seems to be abit lacking on the available libs indeed 😄 

Maybe worth exploring
https://github.com/privicy/onepassword-web-client but probably better to wrap the cli to avoid potential breaking changes.

**Comment by liftedkilt** [comment]
Now that 1Password Secrets Automation has launched (https://support.1password.com/secrets-automation/), it would probably be substantially easier to add this.

The current best workaround would be:

external-secrets -> vault -> secrets-automation

I'd prefer to avoid deploying vault just to bridge this, if at all possible!

**Comment by Flydiverny** [comment]
1password has also made their own operator which still seems to be based on the cli. We made an issue there hoping to get them onboard in officially supporting in the ESO rewrite that's underway! 

https://github.com/1Password/onepassword-operator/issues/22

**Comment by bygui86** [comment]
any news on this?
