### ISSUE TITLE
Option to "restart" Pods when ExternalSecrets are updated

### ISSUE THREAD

**Issue by silasbw** [external-secrets/kubernetes-external-secrets#38]
It is useful to reload the process running inside a container when an `ExternalSecret` is updated (*e.g.*, username/password rotation).  An API to facilitate this feature has been discussed at length in other places (e.g., https://github.com/kubernetes/kubernetes/issues/24957).  In the meantime, there are some hackish approaches that might work well enough:

* Add an option to `ExternalSecrets` to declare that Pods should be deleted after an `ExternalSecret` update (not safe for all types of Pod usage)
* Add an option to `exec` a CLI tool in all containers that depend on the `ExternalSecret`/`Secret` (exposing `exec` to the controller seems like a step backwards for security).
* ...

The first step in making progress on this issue is probably to think through the options above (and maybe others) and augment this issue with a proposal for how to proceed.

**Comment by Flydiverny** [comment]
Perhaps recommending another tool to handle this is better? Haven't tried it but just came by https://github.com/stakater/Reloader which looks interesting.

**Comment by silasbw** [comment]
Oh, cool.  I'd like that idea, but it won't work for the ["Volume frontend" work](https://github.com/godaddy/kubernetes-external-secrets/issues/46#issuecomment-498426782) that's underway, which is going to avoid creating a backing `Secret` and instead write the secret data to a memory-backed volume.

**Comment by Flydiverny** [comment]
Closing this as out of scope for KES.
It might be worth bringing up again for [ESO](https://github.com/external-secrets/external-secrets)
