### ISSUE TITLE
Metric last_state persists after ExternalSecret deleted

### ISSUE THREAD

**Issue by EricHorst** [external-secrets/kubernetes-external-secrets#399]
Great new metric last_state, thanks!

We now have a monitoring rule is in place to watch for failed sync. A sync was failing so I deleted the ExternalSecret. However, last_state does not forget and continues to report -1 on the ExternalSecret that no longer exists. It continues to report success on deleted objects as well.

Clearly this is bad and last_state should stop reporting ExternalSecrets status when they go away.

**Comment by cep21** [comment]
Would love a fix for this too :) 

The line is here:

https://github.com/godaddy/kubernetes-external-secrets/blob/af9147548147a011230850f57c98555c0bbd9325/lib/metrics.js#L33

Once the gauge is set, it needs to be explicitly unset or removed when the external secret is removed.  I think `observeSync` needs a similar "not monitored anymore" callback.  I think prom-client `remove` will cause the metric to stop being reported https://github.com/siimon/prom-client/blob/8d69d1f615bd0f82518292720168c368937fb0dc/lib/gauge.js#L114

One workaround is to restart the external secret daemon when you see the bad gauge.

**Comment by cep21** [comment]
This bug is still around

**Comment by loreleimccollum-work** [comment]
Yeah would love to see a fix for this, its impacting the monitoring of our secrets

**Comment by druesendieb** [comment]
This still haunts our monitoring checks - could you please look into this?

**Comment by Flydiverny** [comment]
While this is still unfortunate please see #864
