### ISSUE TITLE
All logs generated by kubernetes-external-secrets are with INFO severity

### ISSUE THREAD

**Issue by jacek-jablonski** [external-secrets/kubernetes-external-secrets#418]
Hi,

thanks for creating  kubernetes-external-secrets.

I have noticed that all messages are generated with `INFO` severity, even those containing errors:

![log](https://user-images.githubusercontent.com/35669512/86287429-718b9000-bbe8-11ea-9b8e-e3fe46802a68.png)

It would be very useful to distinguish messages by their severity.

**Comment by Flydiverny** [comment]
Is this GCP logs? Stackdriver? 

The log message the screenshot is referring to is in fact not an info message, its a warning. (Seen by `"level": 40`  
https://github.com/godaddy/kubernetes-external-secrets/blob/828d0ced9ed1d8c65457be256b946272719e9067/lib/backends/kv-backend.js#L68

**Comment by jacek-jablonski** [comment]
Yes, this is GCP, Stackdriver. It's warning indeed, but in GCP all messages are INFO type.
