### ISSUE TITLE
When using IRSA, pod sometimes doesn't pick up authentication

### ISSUE THREAD

**Issue by gazal-k** [external-secrets/kubernetes-external-secrets#419]
When using IRSA sometimes the pod doesn't pick it up.

- This might be during first installation.
- Updating to a new version.
- node group update etc.

In such cases, it looks like it's reverting to `NodeInstanceRole`.

```json
{
    "level": 50,
    "time": "2020-07-03T10:49:49.545Z",
    "pid": 18,
    "hostname": "kubernetes-external-secrets-f99d86c6f-z8wnw",
    "message": "User: arn:aws:sts::{accountId}:assumed-role/eksctl-{clusterName}-nodegroup-24b3-NodeInstanceRole-{hash}/i-{instanceId} is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:ap-southeast-2:{accountId}:secret:{secretKey}-nzYAC0",
    "code": "AccessDeniedException",
    "requestId": "{requestId}",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 58.06255465080503,
    "msg": "failure while polling the secret {namespace}/{secretName}",
    "stack": "AccessDeniedException: User: arn:aws:sts::{accountId}:assumed-role/eksctl-{clusterName}-nodegroup-24b3-NodeInstanceRole-{hash}/i-0cee646fefe9d6da9 is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:ap-southeast-2:{accountId}:secret:{secretKey}-nzYAC0\\n    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/json.js:51:27)\\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)\\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)\\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)",
    "type": "Error",
    "v": 1
}
```

When this error occurs, just killing the pod resolves the issue.

Is there some way for the application to do this automatically?
Not sure if exiting the process with error will help. If k8s restarts the pod, I don't know if the mutating admission webhook controller will inject the necessary env vars and volume mounts for IRSA to work.

**Comment by spr-mweber3** [comment]
Having the same issue here. With a simple deletion of the pod a new one spawns immediately and then it works as expected.

**Comment by Flydiverny** [comment]
It would be hard for runtime to know if IRSA was intended and is missing or if the user was intending to use EC2 credentials. I don't think a pod restart will help if the IRSA vars wasn't injected in the pod template to begin with.

**Comment by gazal-k** [comment]
Agreed. Actually I probably looked at this the wrong way.

I suppose the real question is why the application pod is not picking up IRSA in the first place. If the pods have a service account and that SA has the right annotations, then EKS's admission controller is supposed to add relevant Env vars and volume mounts to make IRSA work. Maybe this is just an issue with the version of aws-sdk used or something.

I'll do some more troubleshooting and report back

**Comment by gazal-k** [comment]
#452 looks a related
