### ISSUE TITLE
How to update secrets in the Vault?

### ISSUE THREAD

**Issue by agniveshadhikari** [external-secrets/kubernetes-external-secrets#420]
Is there a way for pods to update the secrets back to the Vault?

I'd like to understand why this feature isn't available yet. Is this a conscious choice to not allow this? Am I somehow following a wrong pattern if I need to do this? How should this scenario be handled?

**Comment by EricHorst** [comment]
I think this is the wrong pattern. Vault should be considered the authoritative source and KES used only as a one-way update of kubernetes secrets from the authoritative Vault source.

A pod could definitely update secrets stored in Vault, but that would be best done using the Vault API directly with an appropriate Vault role for that access.

**Comment by agniveshadhikari** [comment]
> I think this is the wrong pattern.
Can you please explain a bit more? What are the potential issues that you see if we were to design a general solution to this?
I'm curious because this seems to be a general enough problem, but none of the major "external-secrets-in-kubernetes" projects seem to implement this.

**Comment by Flydiverny** [comment]
Hmm pretty sure this was asked before but I can't find it 🤷.
I'm not really sure why you want this feature or what you are expecting to be able to do?
Are you expecting to use kubernetes secrets as the source of truth? For what purpose?

But as you say the purpose of most/all of the external secret operators is to read secret data from outside of k8s and make it available in k8s.
