### ISSUE TITLE
vault k8s auth method gives permission denied 

### ISSUE THREAD

**Issue by nitin-wise** [external-secrets/kubernetes-external-secrets#432]
I have vault cluster deployed in k8s using HA mode, and the UI is available at http://vault-ui.vault service endpoint. 
Configured the k8s auth using instructions here https://www.vaultproject.io/docs/auth/kubernetes

Vault k8s secret path is `kubernetes`

The Service account used above `vault-auth` in `vault` namespace is mapped in the external-secret 
Service account used for k8s auth in vault. 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: vault
  creationTimestamp: "2020-07-09T14:36:11Z"
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-4.0.0
  name: vault-auth
  namespace: vault
  resourceVersion: "594391"
  selfLink: /api/v1/namespaces/vault/serviceaccounts/vault-auth
  uid: 2c0eb8d8-7cf6-4d64-b5d0-e61fff89524b
secrets:
- name: vault-auth-token-6mqd5
```

Above service account is mounted in the external-secret controller 
```
Name:           external-secrets-kubernetes-external-secrets-647548977-55kkj
Namespace:      vault
Labels:         app.kubernetes.io/instance=external-secrets
                app.kubernetes.io/name=kubernetes-external-secrets
                pod-template-hash=647548977
Annotations:    cni.projectcalico.org/podIP: 100.123.148.200/32
Status:         Running
Controlled By:  ReplicaSet/external-secrets-kubernetes-external-secrets-647548977
Containers:
  kubernetes-external-secrets:
    Container ID:   docker://147b4cdb1bea4cb5e86652a978735c2224e1de7cfc420165b449e78ed41271ae
    Image:          godaddy/kubernetes-external-secrets:4.0.0
    Image ID:       docker-pullable://godaddy/kubernetes-external-secrets@sha256:8c12366658599ed6c7e48cf2d7d6bd53612feecd41a44cc0a07298a6028ee05c
    Port:           3001/TCP
    Host Port:      0/TCP
    Environment:
      VAULT_ADDR:                    http://vault-ui.vault:8200
     Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from vault-auth-token-6mqd5 (ro)

```

A secret is `kv` at path secret/ is created using 
```
vault kv put secret/dev/secret @secret.json
```

Below is the manifest for external secret which should create a k8s secret with above secret values from vault. 

```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: secret-rds
  namespace: vault
spec:
  backendType: vault
  vaultMountPoint: kubernetes 
  vaultRole: demo
  data:
  - name: password
    key: secret/dev/secret
    property: password
  separately
  - name: user
    key: secret/dev/secret
    property: user
```

After applying above manifest, the secret fails with error
```
Status:
  Last Sync:            2020-07-13T19:01:38.918Z
  Observed Generation:  1
  Status:               ERROR, 1 error occurred: * permission denied
Events:                 <none>
```

Logs in controller as follows. 
```
{"level":30,"time":1594665707669,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-647548977-55kkj","msg":"running poll on the secret vault/secret-rds"}
{"level":50,"time":1594665707690,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-647548977-55kkj","response":{"statusCode":403,"body":{"errors":["1 error occurred:\n\t* permission denied\n\n"]}},"stack":"Error: 1 error occurred:\n\t* permission denied\n\n\n    at handleVaultResponse (/app/node_modules/node-vault/src/index.js:49:21)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async VaultBackend._get (/app/lib/backends/vault-backend.js:54:28)\n    at async /app/lib/backends/kv-backend.js:29:31\n    at async Promise.all (index 0)\n    at async Promise.all (index 1)\n    at async VaultBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:116:42)\n    at async Poller._createSecretManifest (/app/lib/poller.js:88:18)\n    at async Poller._upsertKubernetesSecret (/app/lib/poller.js:152:28)","type":"Error","msg":"failure while polling the secret vault/secret-rds"}
{"level":30,"time":1594665707706,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-647548977-55kkj","msg":"stopping poller for vault/secret-rds"}
{"level":30,"time":1594665707706,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-647548977-55kkj","msg":"starting poller for vault/secret-rds"}
```

The policy.hcl file for the k8s auth role `demo` is as below with enough priviledges to read the secret/ path. 
```
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "sys/policies/acl/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
path "auth/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
```

Spent a lot of time investigating the issue, and there are very less supporting docs to verify the installation. 
A quick help or suggestions will be appreciated.

**Comment by nitingadekar** [comment]
Awaiting any response on above. Thanks in advance.

**Comment by paperbag-zz** [comment]
If you have vault enabled with kv version 2, you will need to specify this in the external secret and to make sure you use the correct paths. This was released with 4.2.0

`apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: blockchain-gateway-certificates
  namespace: default
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: fn-vault-role
  kvVersion: 2
  data:
  - name: data
    key: kv/data/secret/secret-data
    property: data
`

Please see: 
https://github.com/godaddy/kubernetes-external-secrets/issues/439

**Comment by axozoid** [comment]
From my experience, all the times I saw this error it was coming due to mismatching path&perms defined in the policy that is attached to a Vault's role.

Try these steps for troubleshooting:
1. Run `vault secrets list -detailed` to understand which version of KV secret engine do you use (if doesn't say "version @" - it means its version "1");
2. Run 
```
kubectl -n vault run tmp --rm -i --tty  --serviceaccount=vault-auth --image alpine:3.7
```
to start a container with attached SA that is mapped in Vault.
3. Install tools
```
apk add curl jq
```
4. Prepare envars and login to Vault
```
export VAULT_ADDR=http://vault-ui.vault 
export KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
export VT=$(curl -s --request POST --data '{"jwt": "'"$KUBE_TOKEN"'", "role": "demo"}' $VAULT_ADDR/v1/auth/kubernetes/login | jq -r '.auth.client_token')
```
make sure that $VT isn't empty - there was a different response body in older versions of Vault, so adjust the JSON path above if needed.
5. Try fetching secrets.
Like this:
```
curl -s --header "X-Vault-Token: $VT" $VAULT_ADDR/v1/$SECRET_PATH | jq -r '.data.data'
```
Once you are able to get a secret, use the same path in your manifest.
For eg., with the default setup of Vault and KVv2, your path m be `secret/data/dev/secret`, whereas with KVv2, it may even simply be `dev/secret`. Try different options.
6. I also find it very useful to check API explorer that is available under URL  `VAULT_ADDR/ui/vault/api-explorer` - you may see the exact curl commands for various HTTP API calls. Find your mount, put `location of the secret`  and simulate request.

Good luck.

**Comment by nitingadekar** [comment]
Thanks for the suggestions, My setup is currently destroyed, I will recreate and try again.

**Comment by user-name-is-taken** [comment]
I had this issue because I was using the wrong cert for the kubernetes auth linking. The docs recommend following [the man page](https://www.vaultproject.io/docs/auth/kubernetes) for creating the k8s auth params, I followed [vault's tutorial](https://learn.hashicorp.com/tutorials/vault/agent-kubernetes) which I found much more useful.

**Comment by winkee01** [comment]
Can you explain the cause of this problem? I literally encounter the same issue, the certificate is correctly set and the role policy is also ok. but still, get "permission denied".
