### ISSUE TITLE
RFE: add support to "controller.ingressClass"-like annotations

### ISSUE THREAD

**Issue by marcuz** [external-secrets/kubernetes-external-secrets#438]
Hello,

in our use-case we are fetching secrets from AWS Secrets Manager $region1, but we also have the need of fetching some of them from $region2.
We are working it around having 2 instances of external-secrets running, but they are both consistently failing to fetch the secret from the other region - which is expected.

Would it make sense to consider adding an annotation-driven mechanism similar to what Ingress is doing, as in watching not only per-namespace (as discussed in https://github.com/godaddy/kubernetes-external-secrets/issues/106) but also "filtering responsibilities" of each external-secret instance?

**Comment by moolen** [comment]
The region feature is discussed in #354, i think that should fix your issue (PR is open). Nonetheless having a  `ingressClass` is a good idea and is a valid use-case to shard responsibility (also its part in an attempt to standardize the crd spec #477 ).
