### ISSUE TITLE
Documentation: Vault role

### ISSUE THREAD

**Issue by DirtyCajunRice** [external-secrets/kubernetes-external-secrets#440]
I am only ~12 hours in to using es with vault and I am still confused with the vault role and how it applies. These are things that are not documented (that i can find) that I have no problem documenting with a PR but need clarity on before i do.
* The vault role defined in the external secret maps to a service account name. Does that service account name need to be used to deploy the ES container itself? For example, I deployed via helm and it is running as a service account named `external-secrets-do-kubernetes-external-secrets` (obtuse i know i didnt set override full name). That account needed to be added to the vault role to be able to read secrets even though i specified a different role. 
* Does the namespace the actual es matter? From my tests it doesnt _seem_ like it does as the actual thing calling it is the es container which is in namespace x or y. If it does not i think explicit statement of this during the deployment how-to would help before the link to their docs.

**Comment by Flydiverny** [comment]
> The vault role defined in the external secret maps to a service account name. Does that service account name need to be used to deploy the ES container itself? For example, I deployed via helm and it is running as a service account named external-secrets-do-kubernetes-external-secrets (obtuse i know i didnt set override full name). That account needed to be added to the vault role to be able to read secrets even though i specified a different role.

Maybe @Pluies who made the original vault PR could help here?  

> Does the namespace the actual es matter? From my tests it doesnt seem like it does as the actual thing calling it is the es container which is in namespace x or y. If it does not i think explicit statement of this during the deployment how-to would help before the link to their docs.

Not sure if there's anything vault specific that I'm not aware of. But for kubernes-external-secrets deployment does not really care about namespaces. Regardless of where it runs it will look at all available namespaces. Any external secret will generate a secret in the same namespace as the external secret resource is in. There's a long standing PR to allow KES to watch a single namespace.

**Comment by Pluies** [comment]
Heya 👋 

Disclaimer – I've switched companies and am not using external-secrets here anymore so this will be from memory :)

> The vault role defined in the external secret maps to a service account name. Does that service account name need to be used to deploy the ES container itself? For example, I deployed via helm and it is running as a service account named external-secrets-do-kubernetes-external-secrets (obtuse i know i didnt set override full name). That account needed to be added to the vault role to be able to read secrets even though i specified a different role.

Yes indeed, the [Kubernetes authentication method](https://www.vaultproject.io/docs/auth/kubernetes) requires the external-secrets pod itself to be running as the serviceaccount that maps to a role on the Vault side.

IIRC we were running it on a home-brewed chart, so I can't offer any extra info on the Helm side unfortunately.
