### ISSUE TITLE
[vault backend] support for multitenancy

### ISSUE THREAD

**Issue by raffaelespazzoli** [external-secrets/kubernetes-external-secrets#474]
If I understand correctly, when using Vault as the backend, the external-secrets pod service account is used to retrieved the secrets from vault via the kubernetes authentication method.
This means that every namespace shares the same credentials as far a Vault access goes. 
This obviously does not play well in a multitenant environment in which each namespace is assign to a different tenant and strict isolation between tenants must exist.
Can you confirm that this is the case? 
If it is indeed the case what workarounds do exist?
Here are of a couple proposals:
1. the external-secrets controller can be scoped to watch only one namespace. One controller per namespace will be created. This has the undesirable drawback that a bunch of pods (mostly idle) will need to be created.
2. The external-secrets controller uses a service account of the namespace in which the external secret is defined to perform the kubernetes authentication to vault. The service account can be specified as an additional parameter and it could default to the default service account. This would be the ideal soltion.

**Comment by devth** [comment]
I came here with the same concern.

In our cluster, each namespace gets its own `ServiceAccount` that provides it access to specific paths in vault using a Vault Policy. Number 2 in the above comment would be a nice solution.
