### ISSUE TITLE
Fix charts/kubernetes-external-secrets/README.md

### ISSUE THREAD

**Issue by SatoruItaya** [external-secrets/kubernetes-external-secrets#480]
The default value for `image.tag` is now `5.2.0`.
[charts/kubernetes-external-secrets/README.md](https://github.com/godaddy/kubernetes-external-secrets/blob/master/charts/kubernetes-external-secrets/README.md)
ref:https://github.com/godaddy/kubernetes-external-secrets/blob/master/charts/kubernetes-external-secrets/values.yaml#L76

**Comment by Flydiverny** [comment]
Resolved https://github.com/external-secrets/kubernetes-external-secrets/commit/cf0c02bdf6d7dd2a62941cde2611eef7f8a4a1c3
