### ISSUE TITLE
GCP / Google Cloud KMS backend

### ISSUE THREAD

**Issue by MPV** [external-secrets/kubernetes-external-secrets#50]
Would you be open to supporting GCP secrets too?

For example using the Berglas library?
https://github.com/GoogleCloudPlatform/berglas

**Comment by silasbw** [comment]
We would be interested in supporting GCP too. :100:.

GoDaddy is focused on using AWS internally, and it's possible someone at GoDaddy might pick up GCP secrets support as a side-project / extra curricular, but getting some contributions (anything from a more fleshed out issue with concrete use cases to PRs with code) would help ensure the work gets done.

**Comment by JacopoDaeli** [comment]
@MPV would you like to send out a PR for this?
