### ISSUE TITLE
Suppress npm update check in default `Dockerfile` / start script

### ISSUE THREAD

**Issue by chadlwilson** [external-secrets/kubernetes-external-secrets#502]
Currently external secrets seems to still be trying to do the default `npm update` check.

Mostly it fails in our environment due to lack of connectivity, but a tool like this shouldn't really be trying to do such things over the internet.

Suggest that this is suppressed with one of

* Set environment variable `NO_UPDATE_NOTIFIER=true` in `Dockerfile` or default Helm values
* Add `npm config set update-notifier false` into `Dockerfile`
* Use `--no-update-notifier` flag to `npm start`

**Comment by Flydiverny** [comment]
Guessing just starting the script without npm would be fine as well eg `./bin/daemon.js` or `node ./bin/daemon.js` as is otherwise run by `npm start`
