### ISSUE TITLE
Handling multiple Azure Service principles

### ISSUE THREAD

**Issue by ahmedmus21** [external-secrets/kubernetes-external-secrets#504]
Hi ,

I need to use external-secrets operator to serve different applications in different namespaces , each application is accessing an Azure Key vault using a dedicated service principle (AZURE_CLIENT_ID/PASSWORD). (or maybe even different backend types)

now to handle this situation i have 2 options , which i can see that they are not currently supported , please tell me if there are any workarounds : 

1- Define a way to get the service principle inside the ExternalSecret yaml file , along with the keyvault name and the key .
something like that within the spec definition of the yaml:
` AzureClientId: myServicePrinciple`

2 - Having multiple running instances of the operator with different names , each one has its own defined AZURE_CLIENT_ID/PASSWORD inside its env , but in this case each External secret should define which instance of the running operator pods should be listening to it
something like that within the spec definition of the yaml:
` OperatorInstance: my-external-secrets`

Please tell me if something missing from myside , or whether this is an enhancement that we could start implementing.

Thanks

**Comment by Flydiverny** [comment]
Ideally #193 should be re-implemented and finished eg, option number 2 for you. Running one external-secrets instance per namespace.
