### ISSUE TITLE
Failed to get /openapi/v2 and /swagger.json: unable to get issuer certificate

### ISSUE THREAD

**Issue by elvis-cai** [external-secrets/kubernetes-external-secrets#511]
Hi, we deployed kubernetes-external-secrets with latest helm chart 6.0.0, also tried with old version and seems it is reporting cert issue, we did notice similar issue when we deploy fluentd, just wondering is there anyway we can ignore the ssl check, thanks.
```
npm info it worked if it ends with ok
npm info using npm@6.14.6
npm info using node@v12.18.4
npm info lifecycle kubernetes-external-secrets@6.0.0~prestart: kubernetes-external-secrets@6.0.0
npm info lifecycle kubernetes-external-secrets@6.0.0~start: kubernetes-external-secrets@6.0.0

> kubernetes-external-secrets@6.0.0 start /app
> ./bin/daemon.js

{"level":30,"time":1602550312894,"pid":17,"hostname":"secrets-kubernetes-external-secrets-5b94d44c8d-dfcm9","msg":"loading kube specs"}
Error: Failed to get /openapi/v2 and /swagger.json: unable to get issuer certificate
    at /app/node_modules/kubernetes-client/lib/swagger-client.js:58:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/app/bin/daemon.js:33:3)
npm info lifecycle kubernetes-external-secrets@6.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@6.0.0 start: `./bin/daemon.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kubernetes-external-secrets@6.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 1448ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-10-13T00_51_52_949Z-debug.log```

**Comment by pinkyjpainadath** [comment]
We are also facing same issue.  Did you find a solution for this

"level":30,"time":1607051952619,"pid":17,"hostname":"secret-operator-kubernetes-external-secrets-69dfd97bfb-lz699","msg":"loading kube specs"}
Error: Failed to get /openapi/v2 and /swagger.json: unable to get issuer certificate
    at /app/node_modules/kubernetes-client/lib/swagger-client.js:58:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/app/bin/daemon.js:33:3)
npm info lifecycle kubernetes-external-secrets@6.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@6.0.0 start: `./bin/daemon.js`
npm ERR! Exit status 1

**Comment by carpenike** [comment]
Any of you guys figure this out? Ran into it today with a fresh install to my cluser.

**Comment by able8** [comment]
We are also facing same issue.
```
{"level":"info","time":1620715550779,"pid":17,"hostname":"external-secrets-vault-kubernetes-external-secrets-767b694fr4nm","msg":"loading kube specs"}
Error: Failed to get /openapi/v2 and /swagger.json: unable to get issuer certificate
    at /app/node_modules/kubernetes-client/lib/swagger-client.js:58:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/app/bin/daemon.js:35:3)
npm info lifecycle kubernetes-external-secrets@6.4.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@6.4.0 start: `./bin/daemon.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kubernetes-external-secrets@6.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 1303ms
```

**Comment by able8** [comment]
The root cause is that the cluster CA is an intermediate CA certificate which are not trusted by Nodejs https://github.com/nodejs/node/issues/36453

**Comment by dbeal-wiser** [comment]
is there a temporary workaround for this? appears that neither older nor newer versions of the image do not work either at this point.

**Comment by Flydiverny** [comment]
From what I can tell from other similar issues no not really unless you disable SSL verification entirely.
Setting env variable `NODE_TLS_REJECT_UNAUTHORIZED="0"` would probably work. But this would obviously not be a secure solution.

**Comment by elvis-cai** [comment]
thanks for @able8 suggestioin, since it's only an https endpoint, another option is to create another https k8s endpoint with valid ssl cert and proxy to the previously k8s api endpoint, create a serviceaccount with token auth , and add env KUBECONFIG in kubernetes-external-secrets to point to it.

**Comment by jutley** [comment]
We ran into this issue as well and managed to find a suitable workaround. We used `stunnel` in a sidecar to tunnel from a local HTTP endpoint to the secure HTTPS kube-apiserver endpoint. Then we set the environment variables `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` to point to the tunnel.

Here is our stunnel configuration:

```
CApath=/etc/ssl/certs
verify=1
foreground=yes

[client]
accept=127.0.0.1:8001
connect=10.2.0.1:443
client=yes
```

**Comment by ravigude** [comment]
> From what I can tell from other similar issues no not really unless you disable SSL verification entirely.
> Setting env variable `NODE_TLS_REJECT_UNAUTHORIZED="0"` would probably work. But this would obviously not be a secure solution.

This didnt work either

**Comment by anhnguyen-agilityio** [comment]
Any update on this? just got the same issue :(

**Comment by Flydiverny** [comment]
No, it cannot really be solved by KES.
The Workaround above is probably your best bet. Or explore migrating to ESO https://external-secrets.io/ which is written in Go and thereby doesn't run with nodejs.
