### ISSUE TITLE
Cannot get External-Secrets to work with AWS EKS and Secrets Manager

### ISSUE THREAD

**Issue by udemy-darnone1** [external-secrets/kubernetes-external-secrets#529]
I set this up and and created a values.yaml to override the default values in the chart.  I created a k8s secret called aws-credentials with keys id and key for and IAM user that has admin rights.  I deployed the helm chart, created an AWS secret, and External secret following the documentation. The secret never gets created.  If I do a describe on the external secret object I see and error:

 Status:               ERROR, Missing credentials in config

My values file is as follows.  Looking for solution.

```yaml
env:
  AWS_REGION: us-east-2
  AWS_DEFAULT_REGION: us-east-2

# Create environment variables from existing k8s secrets
envVarsFromSecret:
  AWS_ACCESS_KEY_ID:
    secretKeyRef: aws-credentials
    key: id
  AWS_SECRET_ACCESS_KEY:
    secretKeyRef: aws-credentials
    key: key

serviceAccount:
  annotations: 
    "eks.amazonaws.com/role-arn": 'arn:aws:iam::123456789101:role/secrets-role'
  name: webserver-service-account

securityContext:
  fsGroup: 65534
```

**Comment by udemy-darnone1** [comment]
I set this up and and created a values.yaml to override the default values in the chart.  I created a k8s secret called aws-credentials with keys id and key for and IAM user that has admin rights.  I deployed the helm chart, created an AWS secret, and External secret following the documentation. The secret never gets created.  If I do a describe on the external secret object I see and error:

 Status:               ERROR, Missing credentials in config

My values file is as follows.  Looking for solution.

env:
  AWS_REGION: us-east-2
  AWS_DEFAULT_REGION: us-east-2

# Create environment variables from existing k8s secrets
envVarsFromSecret:
  AWS_ACCESS_KEY_ID:
    secretKeyRef: aws-credentials
    key: id
  AWS_SECRET_ACCESS_KEY:
    secretKeyRef: aws-credentials
    key: key

serviceAccount:
  annotations: 
    "eks.amazonaws.com/role-arn": 'arn:aws:iam::987856413978:role/webserver-secrets-role'
  name: webserver-service-account

securityContext:
  fsGroup: 65534The blues file looks like:

env:
  AWS_REGION: us-east-2
  AWS_DEFAULT_REGION: us-east-2

# Create environment variables from existing k8s secrets
envVarsFromSecret:
  AWS_ACCESS_KEY_ID:
    secretKeyRef: aws-credentials
    key: id
  AWS_SECRET_ACCESS_KEY:
    secretKeyRef: aws-credentials
    key: key

serviceAccount:
  annotations: 
    "eks.amazonaws.com/role-arn": 'arn:aws:iam::123456789101:role/secrets-role'
  name: webserver-service-account

securityContext:
  fsGroup: 65534

**Comment by Flydiverny** [comment]
So first of what type of authentication are you trying to use for AWS?
In the values it looks like you are trying to use both ENV injected credentials and IAM Roles for service account credentials.

(I took the liberty of deleting your comment, and editing the issue. As the comment contained 2 copies of your values, one with the AWS account id which you may or may not be concerned with posting)

**Comment by udemy-darnone1** [comment]
Thanks for modifying my post. So then it is either service accounts or AWS credentials but not both?  So I could really uses someone's input I started with just the service account but then I added the AWS credentials because the external secret status reports ERROR, Missing credentials in config. Logging into the deployment the I can see the credentials are properly set. If I change the serviceAccount.create to false and copy out the annotation and name the generation the Kubernetes yam complains with

Error: failed to parse values.yaml: error converting YAML to JSON: yaml: line 17: did not find expected key

If I uncomment the annotation and name then the serviceaccount yaml is not generated but the deployment still references the name of the service account.  serviceAccountName: {{ template "kubernetes-external-secrets.serviceAccountName" . }}
Commenting out the service account causes the deployment  pod to go status error. 

So I am at a loss.

**Comment by Flydiverny** [comment]
I'm not sure of the exact precedence order but I believe set environment variables will override any other credentials.

There must be a service account, either created, or referenced by name to an already existing service account.
If you do not have any special requirements, I recommend you leave the default `serviceAccount.create: true`, no need to override the name.

If you are trying to use IAM roles for service account then set the annotation, if you are trying to use env variables for credentials then leave the annotation out.

As listed here https://github.com/godaddy/kubernetes-external-secrets#aws-based-backends there is several different ways to provide authentication details for AWS backends. You can only use **one** at a time.

**Comment by udemy-darnone1** [comment]
Markus, 

Thanks for your reply. Set the annotation where - in the deployment or the service account?  And is a role really required in the external secret. So I let the generation define a service account with an annotation specifying a role that has access to retrieve the secret but external secret complained of no credentials. I am attaching the deployment yamls for you reference. If you could point out where Have gone wrong that would-be great. The attached zip extracts to a directory called templates. I have also included the roles trust policy and policy. If you don't mind talking a look see, perhaps there is something horribly wrong with what I am doing.
[templates.zip](https://github.com/godaddy/kubernetes-external-secrets/files/5460041/templates.zip)

**Comment by udemy-darnone1** [comment]
This is what I get:

kubectl get externalsecrets.kubernetes-client.io hello-service 
NAME            LAST SYNC   STATUS                                 AGE

hello-service   0s          ERROR, Missing credentials in config   11s

**Comment by udemy-darnone1** [comment]
Here are the yaml files I am deploying. Tar extracts into templates. Trust relationship and policy are also included along with values.yaml.  The only thing not included is the aws-creds secret. I am still getting reds error from the external secret.   I definitely appreciate your assistance.

[templates.zip](https://github.com/godaddy/kubernetes-external-secrets/files/5460242/templates.zip)

**Comment by Flydiverny** [comment]
Assuming you have a role `arn:aws:iam::123456789101:role/webserver-secrets-role` which has the trust relationship set.
You should be able to 

Set the annotation on the service account refering to this role 
```yaml
serviceAccount:
  annotations: 
    "eks.amazonaws.com/role-arn": 'arn:aws:iam::123456789101:role/webserver-secrets-role'
  name: webserver-service-account
```

Remove the secret envs, eg this section:
```yaml
envVarsFromSecret:
  AWS_ACCESS_KEY_ID:
    secretKeyRef: aws-credentials
    key: id
  AWS_SECRET_ACCESS_KEY:
    secretKeyRef: aws-credentials
    key: key
```

in your external secret resource remove the 
```yaml
  roleArn: arn:aws:iam::123456789101:role/webserver-secrets-role
```

 `roleArn` on an external secret is used to specify additional credentials for that specific secret, it will be assumed by the first role. 

You should be able to confirm that the credentials are picked up by exec into the pod, AWS provides some examples here
https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html

Hopefully that gets you further! I know there is some trouble getting up and running with IRSA, but it should work given all configuration is correct 😄

**Comment by darnone** [comment]
Markus,

I followed your instructions above and I think I am getting closer but I am still not quite there yet. Now I am able to create an external secret but the secret is not getting created with the role I am using. looking at the logs on the deployment pod, it seems that my role is not working correctly and the role being used to access secrets is the NodeInstanceRole instead of the role in the service account. I attached my policy to the NodeInstanceRole and the external secret generated the secret as advertised. So I need to figure out what is going on with my role. Code is attached along with a log snippet. I will keep you posted - that you for your assistance.
[templates.zip](https://github.com/godaddy/kubernetes-external-secrets/files/5469539/templates.zip)

**Comment by Flydiverny** [comment]
NodeInstanceRole is the last fallback in the credential chain. Its always a mystery to me why the IRSA credentials aren't picked up!
One issue is the file permissions for the token file that is mounted but that should be solved with

```yaml
securityContext:
  fsGroup: 65534
```

Best to verify the configuration works without KES first. So the trust relationship is known to be working.

**Comment by darnone** [comment]
I think I figured this out.  I keep destroying and recreating EKS clusters to keep costs down, but I was forgetting to recreate the IODC identity provider. Duh!  I do my best work thinking in the shower.  So this is now working in a us-east-2  1.18 EKS test cluster created from a CentOS 7 machine with kubectl 1.18.8 , aws 2.0.57, helm version 3.34, and eksctl  0.30.0.  I am going redeploy this cluster with a KMS key acticated.  Then I need to move this to our work cluster.  it is EKS 1.17 cluster from a WSL Ubuntu running on Windows10, kubectl 1.17.7, aws  2.0.38, helm 3.3.0, and eksctl 0.28.1 (although eksctl does not come into play). I will keep you posted.

**Comment by darnone** [comment]
Markus,
I got the secret to work again in my test cluster with KMS enabled and I was able to get this to work inmy work cluster. I wanted to really thank you for all of your help, assistance and patience.

David

**Comment by udemy-darnone1** [comment]
Markus,

I do have two remaining questions.  1.) Can this be step for all namespaces in the cluster or does External Secrets need to deploy to each namespace that requires a secret. 2.) Does this support rotating passwords?

David

**Comment by Flydiverny** [comment]
1) KES will watch in all namespaces, currently there's no support for limiting it to a single namespace.

2) By default KES will poll your backend every 10 seconds, you probably want to tweak that for your needs as it can get expensive depending on your amount of secrets, number of keys to fetch, and backend type.
So your secret will be updated if the value changes in the secret store. Having the pods restart or so when the secret updates is not part of KES concerns tho. You could probably utilize something like https://github.com/stakater/Reloader

**Comment by udemy-darnone1** [comment]
Markus,

How do I change the polling?  Is there a parameter in values.yml to do that? So if I understand correctly, external secrets will watch across all namespaces even if it is in a namespace of its own?  If that is the case, how does this work in a cluster with multiple apps each having an external secret.  Would I add multiple roles to the service account and then restrict which roles a namespace is permitted to assume?

**Comment by udemy-darnone1** [comment]
Markus,

I see where I can change polling - I should have take closer look at the deployment.  I have been playing around with deploying ket into it's own namespace and creating secrets others. It is pretty cool. Now I just need to work out the question above with the service account/namespace/password restriction.

**Comment by udemy-darnone1** [comment]
Markus,

Another set of questions if you are willing to answer - these are really design questions.  I want to limit access from different namespaces to specific secrets. First, since this implementation works across all namespaces, there is only one service account.  I presume there are two different ways to approach this.  First, multiple roles pointing to the same serviceaccount for the KES deployment each with different secret policies. Then the service account would have a list of roles as annotations.  The second, one role with a set of policies, one for each secret. The former would restrict namespaceaccess to a role and the latter would allow namespaces to restrict what password they have access to. I have not tried either of these - is one better than the other?  Also, is KES centralized across nodegroups?  Again, I appreciate your help.

**Comment by Flydiverny** [comment]
You can do a setup with multiple IAM roles where the role used by the service account (SA) is allowed to assume the other roles.
You can specify a `roleArn` in a secret to have it be assumed by the SA role when that secret is fetched.
Further you can set annotations on the namespaces `iam.amazonaws.com/permitted` with a regex to limit which `roleArn` pattern or value is allowed for the respective namespace. (details [here](https://github.com/godaddy/kubernetes-external-secrets#using-aws-access-credentials))

Likewise you can use `externalsecrets.kubernetes-client.io/permitted-key-name` to limit which keys are allowed to be fetched in a namespace. (more in readme [here](https://github.com/godaddy/kubernetes-external-secrets#enforcing-naming-conventions-for-backend-keys))

So given a secret key naming pattern of something like `/dev/<namespace>/db-credentials` you could in your namespace set `externalsecrets.kubernetes-client.io/permitted-key-name: /dev/staging/.*` 

The annotation names are configurable.

**Comment by udemy-darnone1** [comment]
Markus,
Thanks for you reply. I am new to AWS so I am difficulty trying to visualize your first two sentences. To make sure I understand, the suggestion is to create a role unique to each external secret that the service account role is allowed to assume.  What kind or role would that external secret have - AWS Service, Another AWS account, Web Identity, etc? Would the policy for that external secret role be the same as what is provided in README for hello-service/password and attached to the external secret role or the service account?

**Comment by udemy-darnone1** [comment]
I guess what you are talking about is this option config in the external-secret:

# optional: specify role to assume when retrieving the data
  roleArn: arn:aws:iam::123456789012:role/test-role

but what would the role look like and that policy would be attached?  I appreciate your time.

**Comment by Flydiverny** [comment]
> I guess what you are talking about is this optional config in the external-secret:

Yes! :)

The role would have trust relationship to your service account role (the one with the webidentity) and the policy would provide access to a subset of your secret manager resources.
So if you use the web UI to create the role you would select 'Another AWS account', I suppose you could select AWS service as well since you will need to edit the trust relationship regardless.

Example trust relationship:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::123456789101:role/webserver-secrets-role"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Policy could look something like this, to limit it to only get resources whose names starting with /development/

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:Get*",
            ],
            "Resource": "arn:aws:secretsmanager:us-east-2:123456789101:secret:/development/*"
        }
    ]
}
```

**Comment by udemy-darnone1** [comment]
Markus,
Thanks for your reply.  So if I understand this correctly, the service account role does not need to specify secret resources in the attached policy.  Instead the roleArn in the external-secret would assume the role of the service account and "drag" it policy along, right?  So then, secret resources don't need to be referenced in the policy attached to the Service Account?  Here is my current SA policy: 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "webserversecret",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": [
                "arn:aws:secretsmanager:us-east-2:987856413978:secret:DB_PASSWORD-40li5F",
                "arn:aws:secretsmanager:us-east-2:987856413978:secret:hello-service/password-9Mgqo5"
            ]
        },
        {
            "Sid": "secretslists",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetRandomPassword",
                "secretsmanager:ListSecrets"
            ],
            "Resource": "*"
        }
    ]
}
```
 Do I simply change it to this?

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "webserversecret",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": “*”
        }
    ]
}
```

**Comment by Flydiverny** [comment]
Correct, if you will be using `roleArn` everywhere, then service account role doesn't need any policy document

**Comment by udemy-darnone1** [comment]
Yeah! I was writing something when you just replied and I lost it.  I was asking what the final service account policy should look like since in the README.md secrets were referenced directly.  But now we are getting policies from the external secrets roles.  Thus the SA just becomes a role with no policy and everything we need comes from the policy attached to the role in the external secret.  Also the `ENFORCE_NAMESPACE_ANNOTATIONS=true` parameter - does that require both annotations or one or the other?  Markus, I really appreciate your time an answers.  I will keep you posted. - David

**Comment by Flydiverny** [comment]
Looks like it requires both annotations to be present.

**Comment by udemy-darnone1** [comment]
Markus, Thanks again for your reply.  Here is where I am:
- I have renamed my service account IAM role to kes-secrets-role and my service account to kes-service -account
- the kes-secrets-role has no policy
- I have reployed KES to a namespace called kes-namespace.  Everything starts up fine - rbac, service, service account, and deployment.
- I have created a role called defender-secrets-role to assume the role of the service account role kes-secrets-role - following your example
- I have created a policy to access secrets at defender/credentials polling you example.  Before I save the role I received a message from IAM about no conditions
```
This policy defines some actions, resources, or conditions that do not provide permissions. To grant access, policies must have an action that has an applicable resource or condition. For details, choose Show remaining Learn more
```
- Then I saved the policy and attached it to the defender-secrets-role
- I created the secrets with:
```
aws secretsmanager create-secret --region us-east-2 --name defender/credentials --secret-string '{"username":"admin","password":"1234”}’
```
- I created a namespace for the external secret called defender-namespace
- I create an external secret called defender-external-secret that uses roleArn to reference the defender-secrets-role
- When deploying the external secret the secret is not created
- The log from the deployment pod shows that assumed-role/defender-secrets-role is not authorized to perform secretsmanager:GetSecetsValue on resource defender-credentials-XXXX

So it appears the role is being assumed correctly but the policy is not correct (given the message from IAM when I created the policy).  There might be permission missing? Would you be willing to take a look at what I have done? My code attached.  The zip file unpacks to templates-kes.  The defender external secret is in the defender directory.  I have also included the IAM stuff as well as the log snippet.

[templates-kes.zip](https://github.com/godaddy/kubernetes-external-secrets/files/5496221/templates-kes.zip)

Markus, I am really grateful for you time and effort assisting and helping me.  I am hoping you can help me determine what is wrong. - David

**Comment by udemy-darnone1** [comment]
Markus,

Don't think the policy for the external likes the "secretsmanager:Get*" (plus you had an extra comma at the end of the line.  When I removed the comma and create the policy you suggested above I received a note from IAM:

```
This policy defines some actions, resources, or conditions that do not provide permissions. To grant access, policies must have an action that has an applicable resource or condition. For details, choose Show remaining Learn more```
```

When I replace that with this:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": "arn:aws:secretsmanager:us-east-2:987856413978:secret:/defender/credentials/*"
        }
    ]
}
```

I did not get the message from IAM.  Still, the log is telling me that I do not have permissions to access AWS secrets manager defender credentials.  Any suggestion on your part is welcome.

**Comment by udemy-darnone1** [comment]
Markus,

I think I have narrowed this down.  I went added the original hello-service/password secret to my defender-secrets-policy and I was able to create the secret using:
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test-es
  namespace: defender-namespace
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::123456789101:role/defender-secrets-role
  region: us-east-2
  data:
    - key: hello-service/password
      name: password
```

I have not been able to get access to passwords created in a json object.  Considering, defender/credentials is the same json object with different name the following fails to create a secret:
```

apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: defender-external-secret
  namespace: defender-namespace
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::987856413978:role/defender-secrets-role
  region: us-east-2
  data:
    - key: /defender/credentials
      name: username
      property: username
#    - key: /defender/credentials
#      name: password
#      property: password
#  dataFrom:
#    - defender/credentials
```

I have tried every combination but can't get that to work. Creating password from a json object is great feature in terms of organizing secrets but I am unable to get it to work.  Also there is a list inconsistency in you readme.  Sometime there is a leading slash, ie /hello-service/credentials and sometimes there isn't.  so I have tried every combo in the secret and in the policy. Your assistance is again much appreciated.

**Comment by udemy-darnone1** [comment]
Markus,

I got the implementation to work. Now onto the iam.amazonaws.com/permitted, externalsecrets.kubernetes-client.io/permitted-key-name:, and ENFORCE_NAMESPACE_ANNOTATIONS=true feature.  I thank you for you assistance - I will keep you posted. - David

**Comment by udemy-darnone1** [comment]
Markus,

If my service account role is kes-secret-role and my external secret role (that assumes the kes-secretsole service account role) is defender-secrets-role, which of these should be mentioned in the iam.amazonaws.com/permitted annotation.  Would this be:
```
iam.amazonaws.com/permitted: "arn:aws:iam::123456789012:role/defender-secrets-role"
```

**Comment by udemy-darnone1** [comment]
Markus,
I just wanted to know that I hot the annotations to work fully - iam.amazonaws.com/permitted, externalsecrets.kubernetes-client.io/permitted-key-name:, and ENFORCE_NAMESPACE_ANNOTATIONS=true. pretty slick. I want to thank you for all of you assistance.  Hopefully, the tread provides some ideas o how to make your readme rock solid including fully examples beginning to end.  I will be ding this for my own purposes and would be willing to have if you are interested. Have a great weekend - David

**Comment by Flydiverny** [comment]
PRs welcome! We should really try to set up a docs site to be able to provide better structure for the docs but lack of time is apparently a thing :)
