### ISSUE TITLE
Azure private cluster and KeyVault not working

### ISSUE THREAD

**Issue by AgarwalAnurag** [external-secrets/kubernetes-external-secrets#536]
I am trying to setup the External Secret within an Azure Private Cluster and Service Principle. But getting below error in the pod --

ERROR, Authentication failed to complete due to the following errors:AuthenticationError: An error was returned while authenticating to Azure Active Directory (status code 400).More details:{ "error": "authority_not_found", "errorDescription": "The specified authority URL was not found."}AuthenticationError: An error was returned while authenticating to Azure Active Directory (status code 400).More details:{ "error": "invalid_request", "errorDescription": "Identity not found"}

This AKS cluster is private with AD + RBAC enabled.

I have create the default secret i.e. azure-credentials

```
cat <<EOF | kubectl apply -f -
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "azure-credentials",
    "namespace": "kubernetes-external-secrets"
  },
  "data": {
    "clientid": "$clientid",
    "clientsecret": "$clientsecret",
    "tenantid": "$tenantid"
  },
  "type": "Opaque"
}
EOF
```

This SP has the Reader role on the KeyVault. 
But i guess it is not even reaching KeyVault. Please suggest if i am missing any configuration.

Thanks.

**Comment by thorker** [comment]
There a many possible problems:
* misconfigured the keyvault name in the CustomResourceDefinition
* dns misconfigured
* the sp must be in the access policy

Hope it ll help.

**Comment by AgarwalAnurag** [comment]
I verified the above items and they all look good to me.
1. keyvault name is fine in CRD
2. I exec in pod  and it is able to nslookup the keyvault dns. Are you referring to any other dns ?
3. SP is configured with List and Get access policy on the keyvault.

Please help experts.
