### ISSUE TITLE
Copied secrets are stored unencrypted by default

### ISSUE THREAD

**Issue by glyn** [external-secrets/kubernetes-external-secrets#538]
The README should mention that using https://github.com/godaddy/kubernetes-external-secrets alone will result in external secrets being stored unencrypted in etcd and therefore open to attack (either via the etcd server or via backups of etcd data).

A solution, which should probably be recommended in the README, is to use a KMS plugin to encrypt the secrets prior to them being stored in etcd.

**Comment by Flydiverny** [comment]
While this is nothing special for KES having it in the docs wont hurt :) PR welcome
