### ISSUE TITLE
[question] Whats the difference between custom resource manager  and the CRD? which is the preferable to use?

### ISSUE THREAD

**Issue by red8888** [external-secrets/kubernetes-external-secrets#539]
Whats the difference between the  custom resource manager  and the CRD?

> Note: --skip-crds is required in order to ensure the custom resource manager is used and will work for backwards compatibility. In future 4.x releases, this will not be required. See below for how to disable the custom resource manager via the chart.

Backward compatibility for what? for k8s or helm or something?

Is it better to use the custom resource manager to install the CRD or the helm chart?

**Comment by Flydiverny** [comment]
Yes, mainly a migration path towards manual installation of CRDs. Currently they are automatically installed by the server when it starts.
You will also have to provide more generous RBAC permissions to KES in case you want it to install the CRDs.
So if one is upgrading to Helm 3 and still want KES to manage its own CRDs then you need to supply `--skip-crds` for helm 3 to ignore the CRDs baked into the helm chart. It probably doesn't really change anything as they will be overwritten once the server starts anyway 🤷
