### ISSUE TITLE
Multi Arch Images, Arm64

### ISSUE THREAD

**Issue by autarchprinceps** [external-secrets/kubernetes-external-secrets#551]
There is no multi arch manifest support in the official image. AWS Graviton instances are very compelling for Kubernetes and most of our other images work transparently with them as well. Setting up a multi arch build isn't very complicated using buildx

**Comment by kg-ops** [comment]
Are there any tentative plans around setting up a multi-arch build ?

**Comment by Flydiverny** [comment]
@kg-ops ideally we would build images in github actions which could include multi arch yes.
Contributions welcome :)

**Comment by Flydiverny** [comment]
This was added
