### ISSUE TITLE
Moving the repository to a new org broke helm repo.

### ISSUE THREAD

**Issue by voldemortensen** [external-secrets/kubernetes-external-secrets#553]
https://godaddy.github.io/kubernetes-external-secrets/index.yaml is now returning 404, which breaks all deployments depending on the chart repo.

https://external-secrets.github.io/kubernetes-external-secrets/index.yaml now hosts repo, but I don't see any documentation or warning of this breaking change.

**Comment by Flydiverny** [comment]
#554 tracks move related issues and readme has been updated with new repo and notice.
