### ISSUE TITLE
Any way to run with reduced logging

### ISSUE THREAD

**Issue by jayzalowitz** [external-secrets/kubernetes-external-secrets#560]
There are a gargantuan amount of INFO logs that we dont need, is there a way to prevent the logging of these?

**Comment by Flydiverny** [comment]
Any specific log messages you would like to see moved to a lower level?
It can be a bit chatty for sure :) you could always raise the log level to warn instead of info. Tho probably not much logged then

**Comment by jayzalowitz** [comment]
So this will do @Flydiverny ?
set {
    name  = "env.LOG_LEVEL"
    value = "warn" 
  }

**Comment by Flydiverny** [comment]
Yes `LOG_LEVEL` can be set to either one of `trace | debug | info | warn | error | fatal | silent`
