### ISSUE TITLE
Binary Files in Secrets with Google Secret Manager

### ISSUE THREAD

**Issue by prabinsubedi** [external-secrets/kubernetes-external-secrets#561]
godaddy/Kubernetes-external-secrets:6.0.0 Controller fails to if the secrets uploaded to the Google secret manager is a binary file and the creation of Kubernetes secrets are encoded from hexadecimal that is encoded by google secret manager.                 

In a nutshell, my question is How to use godaddy/Kubernetes-external-secrets with binary data on Google secret manager?

**Comment by Flydiverny** [comment]
Provide example of your external secret  :))
Did you set `isBinary: true` for the key with binary data?

**Comment by prabinsubedi** [comment]
Hi, 
Thank you for the reply my case I am trying to store .p12 binary file and create the k8s secret with external secrets.  Can you let me know how I can set isBinary: true  as I could not find a way where I can enable. 

Thanks Much.

**Comment by Flydiverny** [comment]
https://github.com/external-secrets/kubernetes-external-secrets/blob/master/examples/hello-service-external-secret-gcp.yml

**Comment by prabinsubedi** [comment]
Hi Flydiverny,
Thank you for the suggestion, and it works for us. The tricky part here is on google secret value, I have to provide base64 coded value of binary data and set isBinary: true. 

Once Again thank you.
