### ISSUE TITLE
Failed to get /openapi/v2 and /swagger.json: Created Component, but require templated one.

### ISSUE THREAD

**Issue by anden-dev** [external-secrets/kubernetes-external-secrets#563]
Hi there,

I have the current kubernetes-external-secrets 6.0.0 running on a couple of eks clusters, and after a pod restart it is crash looping now.

```
npm info it worked if it ends with ok
npm info using npm@6.14.6
npm info using node@v12.18.4
npm info lifecycle kubernetes-external-secrets@6.0.0~prestart: kubernetes-external-secrets@6.0.0
npm info lifecycle kubernetes-external-secrets@6.0.0~start: kubernetes-external-secrets@6.0.0

> kubernetes-external-secrets@6.0.0 start /app
> ./bin/daemon.js

{"level":"info","time":1605871823096,"pid":17,"hostname":"kube-external-secrets-kubernetes-external-secrets-76dbbf4cwkwmg","msg":"loading kube specs"}
Error: Failed to get /openapi/v2 and /swagger.json: Created Component, but require templated one. This is a bug. Please report: https://github.com/silasbw/fluent-openapi/issues
at /app/node_modules/kubernetes-client/lib/swagger-client.js:58:15
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async main (/app/bin/daemon.js:33:3)
npm info lifecycle kubernetes-external-secrets@6.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@6.0.0 start: `./bin/daemon.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kubernetes-external-secrets@6.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 3308ms
```

the clusters are: 

eks 1.17 / eks.3 - v1.17.9  
eks 1.18 / eks.2 - v1.18.9

It is not a cert problem like #511 but also related to swagger-client.
[https://github.com/silasbw/swagger-fluent/issues/55](https://github.com/silasbw/swagger-fluent/issues/55)
[https://github.com/godaddy/kubernetes-client/issues/666](https://github.com/godaddy/kubernetes-client/issues/666)

**Comment by anden-dev** [comment]
hmm #543 looks like my problem, but it was closed with:
_Found the solution for our problem, we needed to revert deployment of kube-metrics-adapter from v0.1.9 to v0.1.8._

Yet I do not have [kube-matrics-adapter](https://github.com/zalando-incubator/kube-metrics-adapter) running in the clusters.

**Comment by Flydiverny** [comment]
Ugh, this seems to come back every now and then. Underlying issue has been that some api resource in the cluster can't be parsed by the dependency KES uses (or well the dependency of our dependency), when the kubernetes api is generated in runtime. :\

**Comment by Flydiverny** [comment]
It's hard to patch without knowing what fails to be processed. Have you upgrades any other resource in the cluster recently since it was last working? Probably something that provides a CRD

**Comment by anden-dev** [comment]
You touch quite the subject there. I am advocating constantly updating charts, and always do: I guess we will have that discussion in my team again.

But CRDS is a good pointer. Thanks.

I will check and get back here: my bet is on prometheus-adapter or kube-prometheus-stack.

**Comment by anden-dev** [comment]
I narrowed it down to [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) the CRDS coming with it  
are causing the crash-loop.

Testet Helm Chart Versions:
12.2.2 (current)
11.1.1
I am still looking for one that is not breaking external-secrets

**Comment by anden-dev** [comment]
I was wrong. 

The problem is coming from [k8s-prometheus-adapter](https://github.com/DirectXMan12/k8s-prometheus-adapter/).

image:  v0.8.2 modifies the openapi

```
k get apiservice v1beta1.custom.metrics.k8s.io 
```

image v0.7.0 is not doing that.

remediation steps: 

1. redploy k8s-prometheus-adapter with image v0.7.0 
2. delete the apiservice coming from v0.8.2
3. restart kubernetes-external-secrets

```
k delete apiservice v1beta1.custom.metrics.k8s.io
```

Everything back to normal.

**Comment by patrickleet** [comment]
so this is still a thing with newer version of prometheus adapter over a year later it seems

**Comment by Flydiverny** [comment]
Well, nothing has really changed on KES side and since its one of the dependencies in KES complaining even if prometheus adapter could probably implement some workaround its not really their issue.

Anyway check out #864
