### ISSUE TITLE
Unable to connect with Vault server

### ISSUE THREAD

**Issue by mcruzdev** [external-secrets/kubernetes-external-secrets#564]
Hi everyone, 
I am trying to use the kubernetes-external-secrets for 2 weeks with vault 
**And I am receiving Error: connect ECONNREFUSED 187.6.211.40:8200** 
I documented all steps:

**kind version 0.9.0**
**vaul helm version 0.8.0**
**kubernetes-external-secrets helm version 6.0.0**

```
kind create cluster --name vault

kubectl create namespace vault

helm install vault hashicorp/vault --set "server.dev.enabled=true" --set "injector.enabled=false" -n vault

kubectl exec -it vault-0 -n vault sh

vault auth enable kubernetes

vault write auth/kubernetes/config \
    token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
    kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" 

vault policy write fmtok8s-policy - <<EOF
path "secret*" {
  capabilities = ["read"]
}
EOF

vault write auth/kubernetes/role/fmtok8s-role \
    bound_service_account_names=fmtok8s-auth \
    bound_service_account_namespaces=vault\
    policies=fmtok8s-policy \
    ttl=24h

vault kv put secret/fmtok8s username=us3rn4m3

helm install kubernetes-external-secrets external-secrets/kubernetes-external-secrets --skip-crds --set env.VAULT_ADDR=http://vault-0:8200 --set serviceAccount.name=fmtok8s-auth -n vault
```
Creating ExternalSecret:
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: fmtok8s-auth
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: fmtok8s-role
  data:
  - name: username
    key: secret/fmtok8s
```

```
kubectl apply -f my-external-secret.yaml -n vault
```

Result:
![image](https://user-images.githubusercontent.com/56329339/100013491-ab397f00-2db3-11eb-82ab-82df82feb111.png)

Log Result:
![image](https://user-images.githubusercontent.com/56329339/100013595-da4ff080-2db3-11eb-9317-468185ce8a84.png)

How I can solve this issue... I used the postman to try the request and I received that:

![image](https://user-images.githubusercontent.com/56329339/100013802-33b81f80-2db4-11eb-8ad6-7df445f55c81.png)
REQUEST:
![image](https://user-images.githubusercontent.com/56329339/100013875-4cc0d080-2db4-11eb-8d1e-20aa57a982e4.png)
RESPONSE:
![image](https://user-images.githubusercontent.com/56329339/100013889-55b1a200-2db4-11eb-8cdb-04cba2633fb1.png)

**Comment by moolen** [comment]
Hey @mcruzdev, i got it to work with `env.VAULT_ADDR=http://vault:8200`. You set `env.VAULT_ADDR=http://vault-0:8200` which shouldn't resolve with your provided helm config. It would resolve if you set the `.spec.clusterIP` to `None`. See [StatefulSet DNS](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) and [Headless Service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services).

It's weird that `vault-0` actually resolves to a public IP. It looks like you're trying to expose vault to the internet? You need an Ingress, service `type=Loadbalancer` or `type=NodePort` to support that.

**Comment by mcruzdev** [comment]
Thank you @moolen, I got it.
In this case, I do not have a headless, then I have just one DNS (vault) entry point as load balancer redistributing to vault-0
With headless I have the DNS vault and individual DNS for other Pods (vault-0, vault-1, vault-2).

I am grateful  👍

**Comment by kocomic** [comment]
same issue. node throw an ECONNREFUSE error while using an external vault domain. my vault is exposed by nginx ingress.

**Comment by kocomic** [comment]
@mcruzdev  Have you sove the problem ?

**Comment by mcruzdev** [comment]
Hi @kocomic,

I solved that and I created a post here https://www.linkedin.com/post/edit/6738512535605035008/

**Comment by kocomic** [comment]
@mcruzdev Sorry, I cant reach that post :), it seems a 'edit' link.

**Comment by mcruzdev** [comment]
> @mcruzdev Sorry, I cant reach that post :), it seems a 'edit' link.

How to use Kubernetes External Secrets (KES) with Vault
https://www.linkedin.com/pulse/how-use-kubernetes-external-secrets-kes-vault-matheus-cruz

**Comment by moolen** [comment]
@mcruzdev thanks for sharing :)
I'll close this one then
