### ISSUE TITLE
Failed to get /openapi/v2 and /swagger.json: unable to get issuer certificate

### ISSUE THREAD

**Issue by pinkyjpainadath** [external-secrets/kubernetes-external-secrets#571]
Getting below error while installation. used latest helm charts. is there a way to skip this check

Error: Failed to get /openapi/v2 and /swagger.json: unable to get issuer certificate
    at /app/node_modules/kubernetes-client/lib/swagger-client.js:58:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/app/bin/daemon.js:33:3)
npm info lifecycle kubernetes-external-secrets@6.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@6.0.0 start: `./bin/daemon.js`
npm ERR! Exit status 1

**Comment by Flydiverny** [comment]
Duplicate #511
