### ISSUE TITLE
Lastpass Support

### ISSUE THREAD

**Issue by kferrone** [external-secrets/kubernetes-external-secrets#575]
Would be very cool to have lastpass as a provider.

There is a CLI: https://github.com/lastpass/lastpass-cli

Unfortunately there are **0** docs on their API. 

Reverse engineer hackathon style anyone? 

Alternatively the CLI could just be embedded, I doubt much people would get behind this.

**Comment by Flydiverny** [comment]
I don't see KES adding support for this. Possibly in the new [project ](https://github.com/external-secrets/external-secrets) down the line, but with no official API it doesn't feel that great :)
