### ISSUE TITLE
IRSA configuration is failing with 6.1.0/5.2.0 release

### ISSUE THREAD

**Issue by jihed** [external-secrets/kubernetes-external-secrets#597]
I am deploying KES on EKS(eks.3 = kube 1.18). The controller is up and running with IRSA configuration. However, it keeps failing to fetch for the secrets from the AWS Secrets Manager using the worker instance profile.

logs:

```
ERROR, User: arn:aws:sts::<account_id>:assumed-role/alz-gdp-pg1-dev-eks2021010820415829350000000e/i-0bbb53922975471c2 is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:eu-central-1:<account_id>:secret:hello-service/credentials-6O9nph"}
```

Below is my configuration:

values.yaml :
```env:
  AWS_REGION: eu-central-1
  AWS_DEFAULT_REGION: eu-central-1
  DISABLE_POLLING: true
  LOG_LEVEL: debug

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam:: <account_id>.:role/kes-sa-role

image:
  repository: <account_id>.dkr.ecr.eu-central-1.amazonaws.com/kubernetes-external-secrets
  tag: 6.1.0 # and for 5.2.0

securityContext:
  fsGroup: 65534
``` 
ServiceAccount:

``` 
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account_id>:role/kes-sa-role
    meta.helm.sh/release-name: kes
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-01-10T22:56:27Z"
  labels:
    app.kubernetes.io/instance: kes
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-6.1.0
  name: kes-kubernetes-external-secrets
  namespace: default
  resourceVersion: "510649"
  selfLink: /api/v1/namespaces/default/serviceaccounts/kes-kubernetes-external-secrets
  uid: 74f04504-aee2-44cd-96de-eab47b9cd2a3
secrets:
  - name: kes-kubernetes-external-secrets-token-zjvx6
  ```

trust-policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::<account_id>:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/3D3B84B370338EB5B8A6728992E7930F"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.eu-central-1.amazonaws.com/id/3D3B84B370338EB5B8A6728992E7930F:sub": "system:serviceaccount:default:kes-kubernetes-external-secrets"
        }
      }
    }
  ]
}
```

**Comment by c4m4** [comment]
I fixed with:

securityContext:
  fsGroup: 1000

the to the fact the node process is running with uid and gid 1000 inside the container

**Comment by jihed** [comment]
thanks @c4m4, it still falls to instance profile.

```
                                                                                                                 AGE
hello-service   5m1s        ERROR, User: arn:aws:sts::<account_id>:assumed-role/alz-gdp-pg1-dev-eks2021010820415829350000000e/i-004293898db050175 is not authorized to pe
rform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:eu-central-1:<account_id>:secret:hello-service/credentials-6O9nph

```

**Comment by c4m4** [comment]
@jihed could you check if you are using the role arn in any secret yaml, you need to specify the role on in the serviceaccount

**Comment by jihed** [comment]
> @jihed could you check if you are using the role arn in any secret yaml, you need to specify the role on in the serviceaccount

I use role only on the ServicAccount. Not on external secrets.

**Comment by c4m4** [comment]
check in your role, if you have the assume policy

**Comment by jihed** [comment]
Here's my assume role policy document:
Am I missing something ?

```{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::<account_id>:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/3D3B84B370338EB5B8A6728992E7930F"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringLike": {
          "oidc.eks.eu-central-1.amazonaws.com/id/3D3B84B370338EB5B8A6728992E7930F:sub": "system:serviceaccount:default:*"
        }
      }
    }
  ]
}```

**Comment by c4m4** [comment]
I am using terraform to create the iam policy, this is what I have:

```
data aws_iam_policy_document external-secrets_read_sc_document {
  statement {
    sid    = "ExternalSecretsRead"
    effect = "Allow"

    actions = [
      "secretsmanager:GetSecretValue",
      "secretsmanager:ListSecrets",
      "secretsmanager:ListSecretVersionIds",
      "secretsmanager:GetResourcePolicy",
      "secretsmanager:DescribeSecret",
    ]

    resources = ["*"]
  }

  statement {
    sid = "externalSecrestAssume"
    effect = "Allow"
    actions = [
      "sts:AssumeRole",
    ]
    resources = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/external-secrets-sc-role*"]
  }
}


```

**Comment by jihed** [comment]
@c4m4 the shared IAM policy is for the iam_role inside ExternalSecrets in the roleArn ?

**Comment by c4m4** [comment]
@jihed yes, I attached the sts policy to the role

**Comment by markthebault** [comment]
I work with @jihed.
The problem comes from a timeout due to the SDK unable to reach the private endpoints. We run it in a private environment and there is no internet connection. We do have all the endpoints required (sts, ssm and secretsmanager) they are reachable from inside the container with the correct IP.

I also tried to set directly the enpoint via the option:
```
env:
          LOCALSTACK: 1
          LOCALSTACK_SM_URL: https://secretsmanager.eu-central-1.amazonaws.com
          LOCALSTACK_SSM_URL: https://ssm.eu-central-1.amazonaws.com
          LOCALSTACK_STS_URL: https://sts.eu-central-1.amazonaws.com
```
however without success, any idea ?

**Comment by Flydiverny** [comment]
@markthebault No ideas but to my understanding it should be possible to get it working looking at earlier issues #232 and #348.
Not sure if you need to set the localstack config to get it working, I don't think so but I suppose it works as an override if you want to force specific endpoints even if its meant for local testing only :)

**Comment by Flydiverny** [comment]
@markthebault Looking at #567 and #601

From #567 
> We use AWS EKS behind HTTP Proxy and use the IRSA feature with AWS Secrets Manager. Since there is no OIDC endpoint available as VPC endpoint, we need to pass a proxy configuration to get a valid session token. (..)

This seems related to the issues you are seeing?

**Comment by guitarrapc** [comment]
From EKS 1.19, SecurityContext is not required anymore.

> see detail: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

**Comment by moolen** [comment]
i think this isn't relevant anymore, closing it.
