### ISSUE TITLE
Feature request: delete `Secret` when backend value is deleted

### ISSUE THREAD

**Issue by martina-if** [external-secrets/kubernetes-external-secrets#598]
I would like to have KES delete `secrets` when an AWS SSM Parameter is deleted. The use case is so that we can set or unset secrets through SSM and that is reflected in the cluster.

The current behavior looks like this:

- An `externalSecret` is created in the cluster pointing to `/parameter1`
- KES creates a `secret` with the value of said parameter
- delete `/parameter1` in AWS console
- the `externalSecret` goes to state ` ERROR, ParameterNotFound: /parameter1 could not be found`
- the `secret` stays in the cluster and is not garbage collected

It would be nice to have an option similar to the ["garbage-collection" that Flux implements](https://docs.fluxcd.io/en/1.17.0/references/garbagecollection.html). With this enabled, a missing parameter would trigger a deletion of the corresponding `secret`.

**Comment by Flydiverny** [comment]
What happens if there are authentication issues or if an external secret references multiple values? Is it just the secret that should be removed or the external secret?
Currently secrets are left in the last "good" state indeed. A deletion of the external secret would also delete the secret.

**Comment by martina-if** [comment]
Hi @Flydiverny thanks for the prompt response! Good questions, I hadn't thought of all the use cases....


> What happens if there are authentication issues

I guess if it had an annotation saying something like "garbage collect this" it should be removed when there are auth issues. I am thinking this could be useful when one wants to remove access to something by removing the source of the secret. In that case we might not want to keep a copy of that secret in the cluster. This is just a made up use case.

> or if an external secret references multiple values?

Ideally the secret that is missing should be removed from the secret?

> So a secret should only exist as long as an external secret is in a good status?

I was thinking this would be the case only when the external secret has that "garage collection" annotation. This also ensures backwards compatibility and no bad surprises.

What do you think? Can you think of a an alternative way I can achieve a similar outcome? I basically want to be able to remove a parameter from SSM and have it removed from the cluster automatically.

**Comment by ldejager** [comment]
> I guess if it had an annotation saying something like "garbage collect this" it should be removed when there are auth issues. I am thinking this could be useful when one wants to remove access to something by removing the source of the secret. In that case we might not want to keep a copy of that secret in the cluster. This is just a made up use case.

I have a requirement from infosec that if an AWS Secrets Manager secret is deleted, it should also be removed from the cluster within a reasonable time frame. One of the workarounds suggested is for AWS Secrets Manager secret to be null valued before being marked for deletion which would result into the credential being "removed" but it's too easy for someone to not follow the process which ends up with sensitive credentials "dangling" in the cluster.

> AWS Secrets Manager enforces a minimum waiting period of 7 days to give you time to update your code. You will not be able to retrieve the secret if it is scheduled for deletion.

Some thoughts around this; during the waiting period (status as shown below indicates it's marked for deletion), perhaps leave the secret in a last "good" state but once the waiting period has elapsed, remove the secret. If the delete is cancelled, the external secret syncs as normal and the secret is kept up to date.

```
NAME                   LAST SYNC   STATUS                                                                                      AGE
test   32m         ERROR, You can't perform this operation on the secret because it was marked for deletion.   9h
```

The external secret should be left behind with a status indicating that the backend was removed, perhaps with a metric endpoint to create visibility/setup alerting on.

If the external secret references multiple backend values, it becomes tricky. Ideally, the referenced properties/values should be removed from the secret, ensuring no sensitive information is left behind but this probably easier said than done and this probably warrants a deeper discussion.

> I basically want to be able to remove a parameter from SSM and have it removed from the cluster automatically.

+1

**Comment by gabegorelick** [comment]
For comparison, the Secrets Store CSI Driver deletes Secrets whenever they're no longer mounted in any Pods, even if it still exists in the backend. I'm not sure what it does if the Secret is in use but deleted on the backend, but in that case you'd have to cycle your pods anyway to get them to stop using the Secret, at which point the Secret would definitely be deleted. 

But this kind of usage tracking is very different from the approach KES uses.

See  https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html.

**Comment by mrkeyiano** [comment]
same issue on Secret Manager, the backend value has been updated and Secret is still using Outdated value
