### ISSUE TITLE
Vault Local Cluster Support

### ISSUE THREAD

**Issue by FalconerTC** [external-secrets/kubernetes-external-secrets#608]
I'm looking to use `kubernetes-external-secret` with Hashicorp Vault on my computer using [kind](https://kind.sigs.k8s.io/). Kubernetes auth can't be done this way because the cluster endpoint is inaccessible (it will be localhost). Any recommendations for how to use this on private clusters?

**Comment by FalconerTC** [comment]
Some options I'm thinking of here are justing adding support for additional auth methods that are possible with a local cluster (approle, gcp, etc) or relying on the Vault agent sidecar and using a different auth form there

**Comment by Nick-Triller** [comment]
@FalconerTC I am having trouble understanding the problem. If Vault and Kubernetes run on the same machine and Kubernetes is reachable via localhost, everything should be fine. Is Vault on a different machine and only kind runs locally?

**Comment by FalconerTC** [comment]
The use case we have is that multiple people are running local Kubernetes clusters that are connecting to a central Vault cluster (so not on the same machine). So to use Kubernetes auth, these clusters have to be exposed and the endpoint+CA registered with Vault, which makes for a lot of management considering the CA is regenerated when a new cluster is created.

The solution we implemented here is to authenticate with a `VAULT_TOKEN` env when using external-secrets with local clusters (via Helm) which our SRE's generate with a script using Okta authentication.

**Comment by Nick-Triller** [comment]
@FalconerTC Interesting solution, thanks for sharing. I think this issue can be closed, no? It appears this is something that can't be solved by the external secrets operator.

**Comment by FalconerTC** [comment]
Yep!
