### ISSUE TITLE
Artifacthub documentation still indicates to use the old helm repo

### ISSUE THREAD

**Issue by zaidenwerg** [external-secrets/kubernetes-external-secrets#619]
Hey 👋🏻
The repo url is not updated on both the artifacthub page and install pop-up 
`helm repo add external-secrets https://godaddy.github.io/kubernetes-external-secrets/`
instead of 
`helm repo add external-secrets https://external-secrets.github.io/kubernetes-external-secrets`
![image](https://user-images.githubusercontent.com/21180010/106767557-a6ab0580-6643-11eb-8668-83c24e5dda92.png)

**Comment by Flydiverny** [comment]
For ref https://github.com/helm/hub/issues/483

**Comment by Flydiverny** [comment]
It should now link to this repo!
