### ISSUE TITLE
bump rbac API version of `rbac.authorization.k8s.io/v1beta1`

### ISSUE THREAD

**Issue by druesendieb** [external-secrets/kubernetes-external-secrets#620]
Hey folks,

the `ClusterRole` and `ClusterRoleBinding` resources are still using `rbac.authorization.k8s.io/v1beta1` which gets deprecated in v1.22 - I wanted to ask about your plans on migrating them to v1?

```
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
```

thanks in advance!

**Comment by Flydiverny** [comment]
Duplicate #516 solved in #609 will be available in next release.
