### ISSUE TITLE
System Manager path scrapping gives spec.data.name and spec.data.key Required value error

### ISSUE THREAD

**Issue by khaleelali** [external-secrets/kubernetes-external-secrets#623]
if i use key and name, the parameter store secrets are pulled correctly. However when i try to install the following yaml i get this error
The ExternalSecret "test" is invalid: 
* spec.data.name: Required value
* spec.data.key: Required value

yaml file contains this
`apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: test
spec:
  backendType: systemManager
  roleArn: arn:aws:iam::123456789012:role/test-role
  region: us-east-1
  data:
    - path: /dev/documentdb
      recursive: true`

**Comment by Flydiverny** [comment]
Feature is not available until next release.

**Comment by Flydiverny** [comment]
@khaleelali 6.3.0 has been released
