### ISSUE TITLE
Retrieving Secrets from Vault throws 404 without any error text.

### ISSUE THREAD

**Issue by abhinavkhanna-sf** [external-secrets/kubernetes-external-secrets#630]
Retrieving Secrets from Vault throws 404 without any error text.

`"payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret <ns>/<external-secret>`

I am unable to debug what I am doing wrong. 

edit:

more logs

```
{"level":30,"time":1613896610435,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-5f45dd675d-lz9jf","msg":"running poll on the secret it-automation/gh-secret"}
{"level":20,"time":1613896610447,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-5f45dd675d-lz9jf","msg":"fetching new token from vault for role it-automation-runner-role on it/kubernetes"}
{"level":20,"time":1613896610450,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-5f45dd675d-lz9jf","msg":"fetching new token from vault for role it-automation-runner-role on it/kubernetes"}
{"level":20,"time":1613896610450,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-5f45dd675d-lz9jf","msg":"fetching new token from vault for role it-automation-runner-role on it/kubernetes"}
{"level":50,"time":1613896610538,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-5f45dd675d-lz9jf","payload":{"response":{"statusCode":404,"body":{"errors":[]}}},"msg":"failure while polling the secret it-automation/gh-secret"}
```

**Comment by sklarsa** [comment]
I'm experiencing the same behavior, but this is when trying to sync kv v2 secrets

**Comment by Flydiverny** [comment]
`"statusCode":404` Seems like it can't find the given secret? 😄

**Comment by sklarsa** [comment]
Sorry @Flydiverny, still adding context, but `vault kv get secret/data/hello-service/credentials` works when running on a separate pod with the same serviceaccount

**Comment by Flydiverny** [comment]
Maybe its failing to get the token, judging by that being the last message before the errors. In that case maybe the vault mount point? But I honestly don't know to much about vault regardless 😄

**Comment by sklarsa** [comment]
No prob! I'm still doing what I can to debug.  The auth seems to be working with `kv v1` secrets, I'm just running into a different error (wanted to keep this ticket clean).
 (With v1 secrets and same yaml)
```
Failed to JSON.parse value for 'kv/data/hello-service/credentials', please verify that your secret value is correctly formatted as JSON. To use plain text secret remove the 'property: password'
```

**Comment by Flydiverny** [comment]
Seems reasonable.
I know the dependency isn't really perfect for kv v2, but to my understanding it should be possible to get it working. But maybe there's something missing. There are some long standing issues https://github.com/kr1sp1n/node-vault/issues/82 perhaps we need to take a look at what they did in [vscode-vault](https://github.com/owenfarrell/vscode-vault/blob/main/src/adaptors/index.ts) and adapt a similar workaround.

**Comment by sklarsa** [comment]
Sounds good... I can try to spin up a dev env at some point today to dig into this a little more

**Comment by Flydiverny** [comment]
Here's an untested idea if you want to experiment :) #642 don't have a vault environment setup currently
