### ISSUE TITLE
Use of deprecated kubernetes-client method .getStream

### ISSUE THREAD

**Issue by Nick-Triller** [external-secrets/kubernetes-external-secrets#638]
I noticed the following log message:
```
Thu, 25 Feb 2021 09:22:24 GMT kubernetes-client deprecated .getStream use .getObjectStream, see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md at lib/external-secret.js:44:10
```
The only use of the deprecated method appears to be here:
https://github.com/external-secrets/kubernetes-external-secrets/blob/85739fde531e64eb329cc4a28264ffc80e29a5f0/lib/external-secret.js#L40-L44

The motivation for the deprecation can be found in the link that is logged: https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md

**Comment by Flydiverny** [comment]
#293 duplicate.

AFAIK the merging efforts stopped and kubernetes-client isn't seeing much development. Ideally we should switch to the official JS client https://github.com/kubernetes-client/javascript but it would require a sizable chunk of work :) 
Did some experiment a while back changing parts of the code to the official client but the issue that we tried to solve remained even with the official lib so a less intrusive fix was made instead.
