### ISSUE TITLE
Consider dual-publishing images additionally to Docker Hub

### ISSUE THREAD

**Issue by chadlwilson** [external-secrets/kubernetes-external-secrets#647]
#587 seemed to switch publishing images to `ghcr.io` only. Would you consider dual publishing to Docker Hub at https://hub.docker.com/r/externalsecrets/kubernetes-external-secrets (not sure who owns this, but seemed to be created around the same time while moving away from the `godaddy` organisation)?

While I appreciate that this may have been done to address rate limiting concerns, some users may take advantage of out-of-the-box mirroring support within Docker for Docker Hub-hosted image to run an internal mirror; reduce queries and exert image control/whitelisting without republishing to an internal repo which (to my knowledge) is not possible with arbitrary repositories.

Could this be considered?

**Comment by Flydiverny** [comment]
It is indeed for the rate limiting concern. We did a request for open source docker hub access but didn't move on with the application in favor of using github, as its easier to manage access and a single place to maintain.

**Comment by henrysachs** [comment]
and what about ecr? as its an aws component mainly it would be beneficial for these to fetch from ecr. :)
