### ISSUE TITLE
Per secret polling interval

### ISSUE THREAD

**Issue by wiseelf** [external-secrets/kubernetes-external-secrets#659]
Is there an opportunity to set a polling interval per a secret? For example for secret that are changing once in month I would like to set polling interval once a day, etc.

Something like:
```apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secret_name
spec:
  backendType: secretsManager
  polling_interval: 86400000
  data:
    - key: secret1
      property: s1
    - key: secret2
      property: s2
```

**Comment by Flydiverny** [comment]
Currently there is no way to set this per ExternalSecret. It is covered in ESO tho! But we still have some ways to go before thats ready, you can check the progress in https://github.com/external-secrets/external-secrets :)
