### ISSUE TITLE
External secrets won't run on ARM based nodes

### ISSUE THREAD

**Issue by spidman** [external-secrets/kubernetes-external-secrets#662]
chart version: 6.4.0

I tried installing external secrets via Helm on EKS running m6g nodes which is ARM-based. I am receiving this error in the external secrets pod:
`standard_init_linux.go:219: exec user process caused: exec format error`

Any plans on making external-secrets Arm compatible in the near future?

**Comment by Flydiverny** [comment]
Please try the new images now available (no release yet) but you can try them from the master tag https://github.com/orgs/external-secrets/packages/container/package/kubernetes-external-secrets

**Comment by arunavamagi** [comment]
> Please try the new images now available (no release yet) but you can try them from the master tag https://github.com/orgs/external-secrets/packages/container/package/kubernetes-external-secrets

Hi @Flydiverny, Thanks for the Multi Architecture Support. Could you please help us with any info on the expected availability of the Release with ARM Support ?

**Comment by Flydiverny** [comment]
@arunavamagi 7.0.0 has now been released :)
