### ISSUE TITLE
Bitwarden Provider

### ISSUE THREAD

**Issue by onedr0p** [external-secrets/kubernetes-external-secrets#675]
Having bitwarden being a provider would be very cool!

They have a cli app written in Node:
https://github.com/bitwarden/cli

**Comment by Lerentis** [comment]
Would still be a cool feature

**Comment by Lerentis** [comment]
Would still be a cool feature

**Comment by Lerentis** [comment]
Do I really need to bump this every 3 months? 😅

**Comment by Flydiverny** [comment]
@Lerentis you could always implement it 😉 

Either way see #864

**Comment by Lerentis** [comment]
Fair point and thanks for the hint on the operator 👍
