### ISSUE TITLE
KES Crashing on "Stopping watch stream for namespace * due to event: END"

### ISSUE THREAD

**Issue by diranged** [external-secrets/kubernetes-external-secrets#707]
We just upgraded from KES 6.0.0 -> 7.1.0 and started seeing the KES pod crash looping. The logs show this:

```
{"level":30,"message_time":"2021-04-14T13:14:33.930Z","pid":18,"hostname":"kubernetes-external-secrets-5b995669c7-s5wqk","msg":"No watch event for 60000 ms, restarting watcher for *"}
{"level":30,"message_time":"2021-04-14T13:14:33.931Z","pid":18,"hostname":"kubernetes-external-secrets-5b995669c7-s5wqk","msg":"Stopping watch stream for namespace * due to event: END"}
{"level":20,"message_time":"2021-04-14T13:14:33.931Z","pid":18,"hostname":"kubernetes-external-secrets-5b995669c7-s5wqk","msg":"Starting watch stream for namespace *"}
TypeError: Cannot read property 'spec' of undefined
    at Daemon.start (/app/lib/daemon.js:68:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@7.1.0 start: `./bin/daemon.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kubernetes-external-secrets@7.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-04-14T13_14_33_948Z-debug.log
```

After digging around, we've found that if we set `WATCH_TIMEOUT` to `120000`, then the crash doesn't happen. (We happen to also set our `POLLER_INTERVAL_MILLISECONDS` to `90000` to keep our API call count down to AWS).

**Comment by rdpa** [comment]
We just upgraded from 7.0.1 to 7.1.0 and are seeing the same error

**Comment by Aenima4six2** [comment]
I posted a PR to fix [here](https://github.com/external-secrets/kubernetes-external-secrets/pull/708/files)

**Comment by Flydiverny** [comment]
Should be resolved in 7.2.0 by #708, thanks @Aenima4six2

**Comment by diranged** [comment]
@Flydiverny,
  Thanks, indeed 7.2.0 does not crash anymore. I will note that it seems to be spamming the logs now though - every 60s it kills the watcher and creates a new one, which prints out all of the ExternalSecrets its watching. Is that really intentional?

**Comment by Flydiverny** [comment]
> Is that really intentional?
Yes, sadly.
You may as noted increase the `WATCH_TIMEOUT`. The reason for the restarting is that the watch stream occasionally hangs after running an unknown amount of time. Preferably the watch stream would have disconnected gracefully and the watcher restart for that reason, but for some reason this does not always happen. There's no way of detecting this and we did try switching kubernetes library but in the javascript world the other libraries also seem to have the same issue. Restarting was a workaround found in another project so we took the same approach here.
