### ISSUE TITLE
"Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1","code":"CredentialsError

### ISSUE THREAD

**Issue by lucasvieirazup** [external-secrets/kubernetes-external-secrets#716]
Hello,

I'm trying to find any error in the chart about miss configuration, appear this message in the api kubernetes-external:

{"level":50,"message_time":"2021-04-23T13:13:53.280Z","pid":17,"hostname":"k8s-vivo-ext-kubernetes-external-secrets-7558dbcd8b-9btn2","payload":{"message":"Missing credentials in config, if using AWS_CONFIG_FILE, set l-secrets:
AWS_SDK_LOAD_CONFIG=1","code":"CredentialsError","time":"2021-04-23T13:13:53.280Z","requestId":"170f88a7-a83c-4816-9d1c-9b026725c10c","statusCode":403,"retryable":false,"retryDelay":95.98201895564404,"originalError":{"message":"Could not load credentials from ChainableTemporaryCredentials","code":"CredentialsError","time":"2021-04-23T13:13:53.280Z","requestId":"170f88a7-a83c-4816-9d1c-9b026725c10c","statusCode":403,"retryable":false,"retryDelay":95.98201895564404,"originalError":{"message":"User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/eksRoleNode/i-0d7eadfb581567e5f is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::330482684181:role/webserver-secrets-role","code":"AccessDenied","time":"2021-04-23T13:13:53.280Z","requestId":"170f88a7-a83c-4816-9d1c-9b026725c10c","statusCode":403,"retryable":false,"retryDelay":95.98201895564404}}},"msg":"failure while polling the secret prod/db-applications"}

I Added AWS_INTERMEDIATE_ROLE_ARN as a Role for eksRoleNode (Is the Role of Nodes in my EKS) and i attached a policy for access a secret manager on that.
My policy to access the secret manager is like this:

{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"secretsmanager:GetResourcePolicy",
"secretsmanager:GetSecretValue",
"secretsmanager:DescribeSecret",
"secretsmanager:ListSecretVersionIds"
],
"Resource": [
"arn:aws:secretsmanager:sa-east-1:xxxxxxxxxxxxxsecretsecret-application-xxxxx",
"arn:aws:secretsmanager:sa-east-1:xxxxxxxxxxxxxsecretsecret-subscription-xxxx",
"arn:aws:secretsmanager:sa-east-1:xxxxxxxxxxxxxsecretsecret-wallet-xxx",
"arn:aws:secretsmanager:sa-east-1:xxxxxxxxxxxxxsecretsecret-camunda-xxxx,
"arn:aws:secretsmanager:sa-east-1:xxxxxxxxxxxxxsecretsecret-password-xxxxx",
"arn:aws:secretsmanager:sa-east-1:xxxxxxxxxxxxxsecretsecret-user-xxxxx",
"arn:aws:secretsmanager:sa-east-1:xxxxxxxxxxxxxsecretsecret-cluster-password-xxx"
]
}
]
}

I my ExternalSecret where i'm deployed, appears the same error of:

db-applications 9s ERROR, Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

Any sugestion about it?

**Comment by sachrajneesh** [comment]
Did you get solution for this error? I am also getting the same error.

**Comment by lucasvieirazup** [comment]
Yeah, i'm still have this error right now:

{"level":50,"message_time":"2021-05-06T21:56:41.656Z","pid":17,"hostname":"k8s-vivo-ext-kubernetes-external-secrets-64dbf454d7-n7w6s","payload":{"message":"Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1","code":"CredentialsError","time":"2021-05-06T21:56:41.656Z","requestId":"996c9438-ca39-4edc-9151-8e8edb08c489","statusCode":403,"retryable":false,"retryDelay":22.788347113797602,"originalError":{"message":"Could not load credentials from ChainableTemporaryCredentials","code":"CredentialsError","time":"2021-05-06T21:56:41.656Z","requestId":"996c9438-ca39-4edc-9151-8e8edb08c489","statusCode":403,"retryable":false,"retryDelay":22.788347113797602,"originalError":{"message":"User: arn:aws:sts::111111111111:assumed-role/eksRoleNode/i-0b98ff847d7237978 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::111111111111:role/webserver-secrets-role","code":"AccessDenied","time":"2021-05-06T21:56:41.655Z","requestId":"996c9438-ca39-4edc-9151-8e8edb08c489","statusCode":403,"retryable":false,"retryDelay":22.788347113797602}}},"msg":"failure while polling the secret prod/db-applications"}
{"level":30,"message_time":"2021-05-06T21:56:41.677Z","pid":17,"hostname":"k8s-vivo-ext-kubernetes-external-secrets-64db

**Comment by sachrajneesh** [comment]
I think you have multiple issues as per my understanding.
