### ISSUE TITLE
region missing from schema

### ISSUE THREAD

**Issue by gabegorelick** [external-secrets/kubernetes-external-secrets#724]
#475 added support for the `region` attribute on ExternalSecrets, but it looks like the schema in the [CRD](https://github.com/external-secrets/kubernetes-external-secrets/blob/master/charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml) was never updated.

**Comment by Flydiverny** [comment]
Yeah, there are a few others missing as well it will be addressed with https://github.com/external-secrets/kubernetes-external-secrets/pull/681 I'll try to fit some time to rebase and wrap that up :)

**Comment by Flydiverny** [comment]
Fixed in 8.0.0 hold of for 8.0.1 tho 😄
