### ISSUE TITLE
Multiple pods during rolling updates

### ISSUE THREAD

**Issue by gabegorelick** [external-secrets/kubernetes-external-secrets#727]
The Helm chart recommends against running multiple replicas: https://github.com/external-secrets/kubernetes-external-secrets/blob/92a69f2e8b4d2096657053e1d4c84bc7345f47aa/charts/kubernetes-external-secrets/values.yaml#L113-L115

However, the default RollingUpdate strategy will cause 2 pods to be running if the deployment is updated. 

![image](https://user-images.githubusercontent.com/610129/116457624-a16bea00-a831-11eb-88f6-32e45d5161ce.png)

It seems like a `Recreate` strategy would maybe be safer if you really want to avoid multiple pods running.

**Comment by Flydiverny** [comment]
PR welcome.
It wont kill your system, but you will get unnecessary calls to your secrets backend, as each replica will react on any changes or polling intervals. Then one of the replicas will most likely fail as it will try to update a resource which is out of date. So there's no value in running multiple replicas other than increased cost and more errors in logs. ESO does leader election so you can run multiple replicas where one will take over if the first one fails.
