### ISSUE TITLE
[Feature Request] Support version of HashiCorp Vault secrets

### ISSUE THREAD

**Issue by rmrfroot** [external-secrets/kubernetes-external-secrets#729]
It would be cool to have optional `version: INTEGER` (now - only latest) for vault backend keys if `kvVersion: 2`.

Usage examples:
1) Rollback of helm releases will automatically rollback secrets.
2) Use different versions of vault secrets at the same time.

**Comment by marianosanswebbeds** [comment]
Any new for that?
Because if you do a **permanetly delete** a secret from vault, the KES continue searching the last version and get a 404 error because the last version created don't exists in Vault.
