### ISSUE TITLE
kubernetes_external_secrets_last_sync_call_state keeps reporting metrics for secrets that have been deleted

### ISSUE THREAD

**Issue by loreleimccollum-work** [external-secrets/kubernetes-external-secrets#732]
We have created monitors with `kubernetes_external_secrets_last_sync_call_state` and have found if you create a bogus secret and delete it, external secrets will keep reporting this secret's metric out until you restart external secrets
It requires a restart after you delete a secret to stop it from reporting metrics on that secret

Is this to be expected that you need to restart external secrets if you purge secrets from your cluster?

**Comment by Flydiverny** [comment]
I guess this is a duplicate of #399

**Comment by loreleimccollum-work** [comment]
Yes it is! sorry I should have searched more on existing issues, I was searching on the metric name but did not find anything

**Comment by Flydiverny** [comment]
Had a hard time finding it myself 😄
