### ISSUE TITLE
Support Azure China Cloud

### ISSUE THREAD

**Issue by goldginkgo** [external-secrets/kubernetes-external-secrets#745]
The kubernetes-external-secrets seems to be not working with Azure China Cloud. 
According to Azure documentation https://docs.microsoft.com/en-us/azure/key-vault/general/security-features#privileged-access, Azure China has different endpoints.
```
Global:
<vault-name>.vault.azure.net:443

Azure China 21Vianet:
<vault-name>.vault.azure.cn:443
```
But from the code, it is only pointing to the Azue global endpoint https://github.com/external-secrets/kubernetes-external-secrets/blob/master/lib/backends/azure-keyvault-backend.js#L20.

Is there any workaround for this?

Thanks.

**Comment by moolen** [comment]
That's not possible yet, but really easy to configure as you have found out already (same issue as #764 )
