### ISSUE TITLE
 ERROR, Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1 

### ISSUE THREAD

**Issue by dolisss** [external-secrets/kubernetes-external-secrets#749]
I am using Kubernetes-external-secret with my Kubernetes cluster that is hosted on ec2 instance. below are my values.yaml file and the secret _(kubectl create secret generic aws-credentials --from-literal=id=xxxx, --from-literal=key=xxx)_ I have created to be used as an env variable. I am getting this error in the externalsecret object.  The external secret pod is running in the same ns and I have also configured the credentials using was cli to bypass this error. what am I missing?[

](url)

**Comment by dolisss** [comment]
[values.yaml.txt](https://github.com/external-secrets/kubernetes-external-secrets/files/6493639/values.yaml.txt)

**Comment by dolisss** [comment]
[values.yaml.txt](https://github.com/external-secrets/kubernetes-external-secrets/files/6493642/values.yaml.txt)

**Comment by moolen** [comment]
My guess would be, that credentials are missing. Are you sure that the secret is in the same namespace as the controller? Can you exec into the container and check if the environment variables are set properly:

```bash
$ env | grep AWS
```

And also check the configured role:

```bash
# prerequisite: install aws cli

# check who you are based on the default credential loading chain
$ aws sts get-caller-identity
{
    "UserId": "XYZ:botocore-session-123",
    "Account": "123412341234",
    "Arn": "arn:aws:sts::123412341234:assumed-role/some-role-i-created/botocore-session-123"
}
 
```

**Comment by qaifshaikh** [comment]
Facing the same issue.
```
ERROR, Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

Output for `$ env | grep AWS_`
```
/app $ env | grep AWS_
AWS_DEFAULT_REGION=us-east-1
AWS_SDK_LOAD_CONFIG=1
AWS_INTERMEDIATE_ROLE_ARN=arn:aws:iam::933794580186:role/secrets_poc
AWS_REGION=us-east-1
```

**Comment by moolen** [comment]
you're missing AWS credentials. If you would use [IRSA](https://aws.amazon.com/de/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) you would see `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` here. If you don't use IRSA you need to specify the [access key/secret](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) credentials:

```
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```
