### ISSUE TITLE
How to trigger a synchronization on-demand?

### ISSUE THREAD

**Issue by KIVagant** [external-secrets/kubernetes-external-secrets#751]
Hi. If the polling interval is configured to a long period, let's say, once per 30 minutes, is there a way to trigger a synchronization on-demand?

**Comment by moolen** [comment]
Just modify the ExternalSecret, that should do it: `kubectl annotate es vault-example foo.bar=77 --overwrite`

**Comment by KIVagant** [comment]
Thank you, @moolen . I will try this. 
Would be nice, though, to have an API or at least a CLI command to re-sync all of the secrets.

**Comment by moolen** [comment]
`kubectl` should be the CLI of choice and you can consume `Kubernetes API Server` as API. I'm a little hesitant adding an extra api for that, the Kubernetes API Server already does authentication, authorization and should handle most (if not all) of use-cases.

**Comment by KIVagant** [comment]
I meant that if one would need to re-sync a group of secrets, they would need to send many API requests to update each ExternalSecret. Thats why I was thinking about an API/CLI call that would say "re-sync everything you have". But I understand that it is not important since the workaround exists. Thank you again, feel free to close the issue if there are no plans in the area.

**Comment by Parad0X** [comment]
@moolen finally got around to implementing your suggestion using `kubectl annotate` but unfortunately it doesn't trigger the sync. (we're on version 8.1.3). Any suggestions?

**Comment by moolen** [comment]
I see, updating the metadata does not trigger a sync :( 
...but we can patch the `spec.template.metadata`, that will trigger a sync!

```bash
kubectl patch es hello-service \
  --patch "{\"spec\":{\"template\":{\"metadata\":{ \"annotations\":{\"force-sync\":\"$(date +%s)\"}}}}}" \
  --type merge
```

**Comment by Parad0X** [comment]
@moolen worked like a charm! Thank you!!!
