### ISSUE TITLE
Improve HA by pulling AWS SM secrets from a list of regions

### ISSUE THREAD

**Issue by andreidum** [external-secrets/kubernetes-external-secrets#761]
Hello,
Given that AWS Secrets Manager supports [secret replication](https://aws.amazon.com/blogs/security/how-to-replicate-secrets-aws-secrets-manager-multiple-regions/) it would be desirable if external-secrets can be configured to pull the secrets from a list of regions, which will improve availability.
Without this feature in place, what solutions are there for those who enable Secret Replication and want to mitigate against AWS Region failure?

**Comment by andreidum** [comment]
Hello, 
Any thoughts on this?

**Comment by Flydiverny** [comment]
As far as I can tell the AWS sdk doesn't really handle this in any way.
But for actually switching the endpoint used you should be able to set `AWS_SSM_ENDPOINT` environment variable, so in case of a region failure I would update this to point to a working region in which case KES should be able to continue working with secret manager. In case of a region failure you would probably need to update `AWS_REGION` environment as well, unless its only secrets manager having issues.
