### ISSUE TITLE
AzureKeyVault integration with Azure Govcloud not working

### ISSUE THREAD

**Issue by lovleshmalik** [external-secrets/kubernetes-external-secrets#764]
Hi,
I was trying ExternalSecret with Azure keyvault located in US GovCloud.
The yaml expects a parameter named "keyVaultName": mykeyvault, which specifies the name of keyvault. 
When trying to fetch credentials from keyvault, the URL that is hit is automatically composed from this as 
 https://mykeyvault.vault.azure.net/secrets/secret1/?api-version=7.1
This means that it is assuming my keyvault is located in public cloud.
My question is , do we have some sort of parameter to tell it to use different cloud, or if that is not an option, can I somehow tell it to pick different endpoint instead of ".vault.azure.net" ?

**Comment by moolen** [comment]
currently, this is hard-coded. You could make that configurable [here](https://github.com/external-secrets/kubernetes-external-secrets/blob/22e6dd8f016aee8cf2e061eeee197f0deafb784d/lib/backends/azure-keyvault-backend.js#L20). Also, there's a external-secrets rewrite in go. Unfortunately, the Azure KV provider is not ready yet (but will be very soon): https://github.com/external-secrets/external-secrets

**Comment by ericabramov** [comment]
Contributing a fix for that:
https://github.com/external-secrets/kubernetes-external-secrets/pull/871
