### ISSUE TITLE
Use helm-docs for documenting the helm chart settings

### ISSUE THREAD

**Issue by red8888** [external-secrets/kubernetes-external-secrets#775]
I wanted to suggest this because I just started using this thing to document my own charts: https://github.com/norwoodj/helm-docs

Its trivial to use, just install the tool, use its comment syntax in your Chart.yaml and values.yaml and your done! You can customize it, but so far I haven't needed to use my own templating for it, just let it read the chart.yaml and values.yaml. It has examples in the repo for setting up precommit hooks as well.

I opened a PR a long time ago and remember having to update the docs manually for the chart. I wanted to see if you guys would find helm-docs useful- I think its great!

**Comment by Flydiverny** [comment]
We actually use it in the go rewrite repo [external-secrets/external-secrets](https://github.com/external-secrets/external-secrets)!
I'm open to a PR 👍
