### ISSUE TITLE
Proposal: Ability to restart specific pod/depolyment on specific secret change.

### ISSUE THREAD

**Issue by alexku7** [external-secrets/kubernetes-external-secrets#778]
Sometimes we need to ensure that the pod has been restarted to mount recently updated secret (kind of secret rotation)

It will be great if the externl secrets operator will restart automatically specific deployment/pod/sts/daemonset if some secret has been changed.  It could be done , for example by some special annotations defined on the externalsecret object .

**Comment by Flydiverny** [comment]
https://github.com/stakater/Reloader would probably cover your needs!

This is something we feel is out of scope for KES.
