### ISSUE TITLE
secrets syncing with error

### ISSUE THREAD

**Issue by gilbert-sam-tm** [external-secrets/kubernetes-external-secrets#783]
Hi, after upgrading our cluster version to eks 1.20.

We are seeing the below error with all our secrets. 

secret-name                           11m         ERROR, getaddrinfo EAI_AGAIN ssm.us-west-2.amazonaws.com   6d6h
Our Kubernetes-external secret version is 6.0.0.

We also upgraded the the latest Kubernetes-external secret version, that did not help either.

Any advise?

**Comment by trucnguyenlam** [comment]
@gilbert-sam-tm please let me know why this issue is close, we encountered a similar one
```
ERROR, getaddrinfo EAI_AGAIN secretsmanager.eu-west-1.amazonaws.com
```

**Comment by gilbert-sam-tm** [comment]
Hi @trucnguyenlam  our core dns had issues, once we resolved it the kubernetes external secret started working.

**Comment by trucnguyenlam** [comment]
@gilbert-sam-tm thanks 👍 I also figured that out the other day, also from core dns.
