### ISSUE TITLE
k8s swagger error on strtup

### ISSUE THREAD

**Issue by Keramblock** [external-secrets/kubernetes-external-secrets#786]
Hi, on 8.2.1 version I have following error right now:
`> kubernetes-external-secrets@8.2.1 start /app
> ./bin/daemon.js
{"level":30,"message_time":"2021-07-05T13:50:53.882Z","pid":19,"hostname":"vault-external-secrets-kubernetes-external-secrets-5fc8c6f2jz9x","msg":"loading kube specs"}
Error: Failed to get /openapi/v2 and /swagger.json: Created Component, but require templated one. This is a bug. Please report: https://github.com/silasbw/fluent-openapi/issues
    at /app/node_modules/kubernetes-client/lib/swagger-client.js:58:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/app/bin/daemon.js:35:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@8.2.1 start: `./bin/daemon.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kubernetes-external-secrets@8.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-07-05T13_50_54_068Z-debug.log`

Am I doing it wrong? Sadly this error doesnt tell me anything I may misconifure, it worked like a charm before update.

**Comment by Keramblock** [comment]
Now it is running again, dk why this was happening

**Comment by Keramblock** [comment]
feel free to close this one

**Comment by Flydiverny** [comment]
Checkout #576 

Closing as duplicate even tho KES versions differ, the underlying issue is still the same 😄
