### ISSUE TITLE
Support for Yandex Lockbox

### ISSUE THREAD

**Issue by AndreyZamyslov** [external-secrets/kubernetes-external-secrets#798]
Hi,

I'm a developer at [Yandex.Cloud](https://cloud.yandex.com).
We would really like to support [Yandex Lockbox](https://cloud.yandex.com/en-ru/docs/lockbox/) as an External Secrets backend.

Is it a good idea to start right with a PR?
Does this kind of change have a chance to be approved?

**Comment by moolen** [comment]
Hey @AndreyZamyslov, by the way we're working on a rewrite in go, you can take a look at it here: https://github.com/external-secrets/external-secrets you're welcome to add a `Yandex Lockbox` provider there as development of new features in `kubernetes-external-secrets` is more or less stalled.

Maybe create an issue there and we can discuss details there. From a quick glance at the Lockbox API Docs it looks pretty straight forward to implement that.
