### ISSUE TITLE
Feature Request - Support for Immutable Secrets

### ISSUE THREAD

**Issue by vikas027** [external-secrets/kubernetes-external-secrets#806]
It would be great to have support for [immutable](https://kubernetes.io/docs/concepts/configuration/secret/#secret-immutable) kubernetes secrets 

Please vote on this issue by adding a 👍  reaction to the original issue to help the community and maintainers prioritize this request

**Comment by Flydiverny** [comment]
Take a look at ESO https://github.com/external-secrets/external-secrets/ ! :) 
Support for Immutable Secrets where recently added there

**Comment by vikas027** [comment]
> Take a look at ESO 

Sorry, what's ESO?

**Comment by Flydiverny** [comment]
> > Take a look at ESO
> 
> Sorry, what's ESO?

Follow the link next to the text you quoted.
https://github.com/external-secrets/external-secrets/

See #864

**Comment by vikas027** [comment]
Ah got your now, KES is deprecated now :(
