### ISSUE TITLE
Is it possible to reload the ExternalSecrets resource? 

### ISSUE THREAD

**Issue by Artemkulish** [external-secrets/kubernetes-external-secrets#834]
Even though it is possible to set up automatic polling of secrets, it would be great to have a possibility to either trigger SYNCs when necessary or make an API call to reload/restart the ExternalSecrets resource so that it could fetch fresh secrets when needed.

I was unable to find a way to either trigger a sync or reload the resource, please let me know if it is possible.

**Comment by mvoitko** [comment]
How to set up automatic secrets polling from AWS SSM?

**Comment by Flydiverny** [comment]
@Artemkulish There is no API or so, however I believe you should be able to annotate the ExternalSecret to trigger a sync.
