### ISSUE TITLE
Add ability to have plaintext, non-sensitive data rendered in the Secret's .spec.template.

### ISSUE THREAD

**Issue by jwtracy** [external-secrets/kubernetes-external-secrets#835]
I would like to use the same lodash templating to render secret and non-secret data into a file.

The fact is that a file with both sensitive and non-sensitive environment specific data is still a sensitive file. It makes sense to create such a file in an ExternalSecret. For non-sensitive and repeated data like a callback URI, project ID, or even just environment name, these keys and values should be specified in the ExternalSecret.

**Comment by javier-b-perez** [comment]
+1

**Comment by jwtracy** [comment]
Is there anyone who can help address this? I have proposed a PR, https://github.com/external-secrets/kubernetes-external-secrets/pull/790.

Also, this proposed revision is working for my company in production use cases.

**Comment by Flydiverny** [comment]
Please see #864 for some info in current project standings :)

**Comment by jwtracy** [comment]
Thanks! I'll look into upgrading and porting!
