### ISSUE TITLE
CyberArk / Conjur backend type?

### ISSUE THREAD

**Issue by tomcruise81** [external-secrets/kubernetes-external-secrets#844]
Any thought been given to implementing a CyberArk / Conjur backend type? 

They currently offer their [CyberArk Secrets Provider for Kubernetes](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Integrations/k8s-ocp/cjr-secrets-provider-lp.htm?tocpath=Integrations%7COpenShift%252FKubernetes%7CSet%20Up%20Applications%7CSecrets%20Provider%20for%20Kubernetes%7C_____0). However, it doesn't quite coincide with the great work that you all have done in this project.

**Comment by 250788** [comment]
Any news or roadmap for supporting CyberArk Conjur as vault backend?

**Comment by Flydiverny** [comment]
See #864

**Comment by Flydiverny** [comment]
@250788 Please file a feature request in ESO :)

**Comment by tomcruise81** [comment]
@250788, thanks for opening https://github.com/external-secrets/external-secrets/issues/588
