### ISSUE TITLE
Secret changes due to polling triggering rolling deploy

### ISSUE THREAD

**Issue by tomcruise81** [external-secrets/kubernetes-external-secrets#845]
Some of the backends that you provide interaction with include polling. With polling, a changed secret (possibly due to password rotation) could be reflected in an updated `Secret`.

I can't find any documentation in your repo about providing a means of having `Secret` updates trigger a rolling deploy for those components that refer to the given `Secrets`. I wasn't sure if you all had a best practice, or if you'd recommend using something like https://github.com/wave-k8s/wave.

Any recommendations would be great. Thanks!

**Comment by Flydiverny** [comment]
Looking at https://github.com/stakater/Reloader or https://github.com/wave-k8s/wave would indeed be the way to go :)

**Comment by tomcruise81** [comment]
@Flydiverny - thanks so much!
