### ISSUE TITLE
Github-Pages Down?

### ISSUE THREAD

**Issue by Silvanoc** [external-secrets/kubernetes-external-secrets#851]
Installation fails with error message
```
Error: failed to download "external-secrets/kubernetes-external-secrets" at version "8.3.0"
```
and I get an error 404 when going to the corresponding URL https://external-secrets.github.io/kubernetes-external-secrets/

Is there something wrong on the pages? On GitHub? No idea.

**Comment by Flydiverny** [comment]
Seems to be available as expected https://external-secrets.github.io/kubernetes-external-secrets/index.yaml
