### ISSUE TITLE
external-secrets stop creating some of the secrets

### ISSUE THREAD

**Issue by liyaka** [external-secrets/kubernetes-external-secrets#866]
We have a very busy EKS development cluster where namespaces with secrets and applications are created and removed all the time. We use external secrets to create secrets in such namespaces when deploying our infra application, there are at least 7 external secrets.
Once in a while some of the secrets are not created - i see the external secret in the namespace and not all secrets are created. In the external-secrets log i see this:

> ```ials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:00.795Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:00.795Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:00.795Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:00.795Z","originalError":{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:00.794Z","originalError":{"message":"Client network socket disconnected before secure TLS connection was established","code":"NetworkingError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:45:49.324Z"},"retryDelay":186.0076279115442},"retryDelay":7.752224663536511},"retryDelay":7.210634532545646},"retryDelay":4.130292462494367},"retryDelay":39.7968112037085},"retryDelay":4.5858668539462855},"retryDelay":8.517199548393162},"retryDelay":57.855636366908},"retryDelay":147.91080930572406},"retryDelay":44.94206447695519},"retryDelay":15.535082595032401},"retryDelay":198.83007601770566},"retryDelay":92.35486046692816},"retryDelay":25.10744711217616},"retryDelay":56.211759327085886},"retryDelay":128.0220929584985},"retryDelay":153.6397010575084},"retryDelay":152.6375446550802},"retryDelay":177.55334121621198},"retryDelay":166.86894797727126},"retryDelay":135.0322866827956},"retryDelay":51.819878358432625},"retryDelay":167.74008797595226},"retryDelay":174.2949556537366},"retryDelay":10.72182693341408},"retryDelay":115.43141020277585},"retryDelay":128.872900693605},"retryDelay":77.8050263073054},"retryDelay":125.13667115076674},"retryDelay":187.49792988123457},"retryDelay":92.35387387642673},"retryDelay":107.14676537763941},"retryDelay":95.7706098929477},"retryDelay":175.27916616846366},"retryDelay":67.78146736889413},"retryDelay":121.53513850976583},"retryDelay":73.48798692798711},"retryDelay":136.93843882345996},"retryDelay":78.74971829432175},"retryDelay":69.517506979291},"retryDelay":89.69624149009046},"retryDelay":103.5438012263413},"retryDelay":74.54587604656213},"retryDelay":73.22439014398606},"retryDelay":197.60897142172502},"retryDelay":128.73885682924478},"retryDelay":163.90334460386785},"retryDelay":166.27153473132083},"retryDelay":190.902875481352},"retryDelay":83.14135772053004},"retryDelay":123.27704466731069},"retryDelay":49.61254076401494},"retryDelay":112.22241352634069},"retryDelay":133.12804943534186},"retryDelay":24.229341256805714},"retryDelay":71.30334210848042},"retryDelay":42.37645738544056},"retryDelay":24.904953185494215},"retryDelay":184.50760300851155},"retryDelay":115.02817580176048},"retryDelay":152.61763895927857},"retryDelay":180.7358197120192},"retryDelay":129.62936180515095},"retryDelay":36.72159740081007},"retryDelay":183.48482550939931},"retryDelay":79.30623594432338},"retryDelay":139.86800278977722},"retryDelay":184.18229196843492},"retryDelay":108.51957370785779},"retryDelay":174.00991317000782},"retryDelay":112.00704230086194},"retryDelay":116.52051850714935},"retryDelay":8.408905632821018},"retryDelay":43.52780956010211},"retryDelay":12.048559085934052},"retryDelay":147.53676690303098},"retryDelay":149.16260366773102},"retryDelay":35.28163871827199},"retryDelay":182.43886178873558},"retryDelay":185.77621368740802},"retryDelay":117.39779878784815},"retryDelay":138.24793803320148},"retryDelay":18.489913745420417},"retryDelay":75.01680323403237},"retryDelay":27.633436484598704},"retryDelay":26.015100078047126},"retryDelay":57.261640890357015},"retryDelay":20.095192058625777},"retryDelay":21.361787211311302},"retryDelay":95.34088307057678},"retryDelay":121.41399329640183},"retryDelay":161.21519051782482},"retryDelay":67.03279027695572},"retryDelay":198.37547303043448},"retryDelay":17.803567548767198},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"retryDelay":165.88302249676067},"msg":"failure while polling the secret xxx/yyy"}```

I'm not sure what this error means - 
```{"message":"Could not load credentials from TokenFileWebIdentityCredentials","code":"CredentialsError","path":null,"host":"sts.amazonaws.com","port":443,"region":"us-east-1","hostname":"sts.amazonaws.com","retryable":true,"time":"2021-11-04T15:46:08.505Z","originalError":``` since we are in eu-west-1 region ... and the nesting retryDelay ..
Deleting the pod "fixed" the problem.

**Comment by chenco166** [comment]
Also happens here on external-secrets version 8.5.0.
external-secrets stopped creating new secrets and it's not processing new ExternalSecrets manifests.
nothing written to logs and pod deletion brings everything back to work.
I've seen this behavior on 5 GKE clusters already.
any idea?

**Comment by Flydiverny** [comment]
Start planning for switching to ESO 
- #864
