### ISSUE TITLE
Fetch all Azure KeyVault secrets

### ISSUE THREAD

**Issue by monti-python** [external-secrets/kubernetes-external-secrets#880]
When many secrets are maintained in a single Azure KeyVault, it becomes rather cumbersome having to specify each secret twice, once in the KeyVault itself and again on the manifest for kubernetes-external-secrets.
It would be ideal if we could map a predetermined path (e.g. `secrets`) to the entire list of secrets. So they are added/removed dynamically.

**Comment by monti-python** [comment]
I've made a PR with the suggested feature: #881

**Comment by Flydiverny** [comment]
Hi @monti-python,
please see:
- #864

**Comment by monti-python** [comment]
Oh, apologies I hadn't seen it... Thanks for the notice @Flydiverny !
