### ISSUE TITLE
Status update failed for externalsecret due to modification, new poller should start

### ISSUE THREAD

**Issue by mrojasbb** [external-secrets/kubernetes-external-secrets#885]
This error has been prompted in our external secrets, but I don't know what could be the cause of a failing when updating the status. Any ideas?

> status update failed for externalsecret this._namespace/this._name, due to modification, new poller should start

Thanks a lot and sorry if any inconvenience.

**Comment by Flydiverny** [comment]
Are you running multiple replicas of the kes operator?

**Comment by matiri132** [comment]
I have the same issue. I'm running to external secrets operator in the same cluser to make a migration. 
I configured the watched_namespace variable and each one is looking in the corrects namespaces but still having that error. And the external secrets resource gave me a 404. 
Any idea @Flydiverny ?

**Comment by wufengzlw** [comment]
Hi, I have the same issue, external-secret with AWS Secrets manager, any update?
`status update failed for externalsecret {namespace}/{secret_name}, due to modification, new poller should start`

**Comment by Flydiverny** [comment]
- #864

**Comment by mrojasbb** [comment]
Oof, time flies.
I figured out how to solve this and it was adding these commands in the readinessProbe (due to we want the secrets being valid when the pods start to work)
`
exec:
              command:
              - bash
              - "-c"
              - |
                redis-cli -a $REDIS_SECRET ping && redis-cli -a $REDIS_SECRET && redis-cli -a $REDIS_SECRET acl setuser default on ">$REDIS_SECRET_ALTERNATE" ~* +@all
`
(Pardon if the indentation is too wrong, but don't know how to put it in a block comment)
With that, we ensure the two secrets are valid and work to authenticate.
Thanks a lot!!

**Comment by mrojasbb** [comment]
The problem hasn't showed to me again, so I trully don't know the cause. Either way, thanks a lot!!
