### ISSUE TITLE
Upsert secret from AWS parameter store as is without base64 encoding

### ISSUE THREAD

**Issue by y0zg** [external-secrets/kubernetes-external-secrets#893]
I have a complex secret(config like) which fails during saving as is in AWS parameter store due to many inherited parameters like `{{ }}`.
So, I encoded that secret to base64 format, but the problem is that ExternalSecrets while creating Secret also encodes the secret, thus I have double-encoded base64 secret. Any ideas how to mitigate this on ExternalSecrets side to have plaintext inserted into Secret? Tried to use `stringData` but didn't get any expected result

**Comment by Flydiverny** [comment]
This section is probably helpful https://github.com/external-secrets/kubernetes-external-secrets#binary-secrets
