### ISSUE TITLE
Feature: add envVarsFromFieldRef  to chart

### ISSUE THREAD

**Issue by emenaceb** [external-secrets/kubernetes-external-secrets#903]
Add a envVarsFromFieldRef to be able to configure the deployment env vars using field refs (valueFrom.fieldRef) according to 
https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-field-selector/#ObjectFieldSelector

The main purpose is to configure env.WATCHED_NAMESPACES with the namespace where the controller is deployed

**Comment by Flydiverny** [comment]
Please see KES deprecation announcement
- #864
