### ISSUE TITLE
Will this work on google container engine kubernetes?

### ISSUE THREAD

**Issue by red8888** [external-secrets/kubernetes-external-secrets#92]
On EKS I can just use roles but if Im on GKE I cant to that

Can I use the default AWS environment variables to set the secret access key and id so I can create an IAM user my gke clusters can use to get access to secrets manager?

**Comment by silasbw** [comment]
Yep, that sounds like it should work, but I haven't heard of anyone trying that yet.  If you try it out and it works let us know or send us a PR to update the README.md.

**Comment by ajaysheoran2323** [comment]
@red8888  Are you able to use this process for GKE?

**Comment by red8888** [comment]
haven't tested yet but will soon. I mean its a pretty quick test, just set the AWS key and secret key env vars. you could probably just pull the container and run locally to test this I suspect

It looks like this is intended to run on EKS with AWS roles which means they are probably instantiating the clients without specifying creds/roles. If thats the case then this should totally work- all the AWS APIs look for those creds by default

**Comment by red8888** [comment]
Tried this but does not appear to be working I am seeing this int he logs:
"failure while polling the secrets {}"   
Im not seeing what the actual error is beyond that message

I confirmed these env vars are set in the pod and the creds have access to get my secrets:
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY

**Comment by red8888** [comment]
ok @silasbw I just cloned this repo and to add some additional logging messages and pushed the image to gcr to test

when deploying with that image Its totally working now- I made no code changes other than adding some log messages

Was this fixed and there is a new release waiting to be cut or something? before I was running the latest image (godaddy/kubernetes-external-secrets:latest)

**Comment by red8888** [comment]
OK! im dumb your "latest" tag is 4 months old. I pulled the actual latest tag "1.3.0" and now its working yay!

Can I send a PR or could someone just up the chart with support for env vars from secrets? I wouldn't hard code params for aws keys it could easily be more dynamic and just support hydrating env vars from _any_ k8s secret

I have been doing this in my charts which works really well for me:

values.yaml:
```
  # define env vars to be created from existing k8s secrets
  envVarsFromSecret:
    AWS_ACCESS_KEY_ID:
      secretKeyRef: aws-credentials
      key: id
    AWS_SECRET_ACCESS_KEY:
      secretKeyRef: aws-credentials
      key: key
```

Then in the deployment:
```
    .......
    spec:
      serviceAccountName: {{ template "kubernetes-external-secrets.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- range $name, $value := .Values.env }}
          {{- if not (empty $value) }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          # For all env vars defined in envVarsFromSecret
          {{- range $key, $value := .Values.envVarsFromSecret }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $value.secretKeyRef | quote }}
                key: {{ $value.key | quote }}
          {{- end }}
          .....
```

**Comment by silasbw** [comment]
@red8888 , thanks for figuring this out!  I'll add updating `:latest` to the deploy script.

We'd appreciate a PR for the changes you mention above :)

**Comment by silasbw** [comment]
Didn't mean to close.
