### ISSUE TITLE
How to configure multiple AWS accounts

### ISSUE THREAD

**Issue by uxth** [external-secrets/kubernetes-external-secrets#920]
Hello
I have a question about multiple AWS accounts where I could not find any answers, maybe you can help to figure it out.

I have multiple AWS accounts, I need to retrieve multiple secrets from multiple secrets manager in these accounts.
But from the helm chart, it only have one pair of the access key id and secret access key.
The question being, is it possible to configure multiple AWS access key id and secret access key pairs?
if yes, please provide an example.
if no, is there any work arounds to achieve this goal?

thanks

**Comment by Flydiverny** [comment]
See
- #864

**Comment by uxth** [comment]
gotcha, thank you.
