### ISSUE TITLE
unable to pull image "godaddy/kubernetes-external-secrets:6.0.0"

### ISSUE THREAD

**Issue by harsha448** [external-secrets/kubernetes-external-secrets#928]
Has been using the image from past 1 and half year ,started to see this issue from past few days

Failed to pull image "godaddy/kubernetes-external-secrets:6.0.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for godaddy/kubernetes-external-secrets, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by Flydiverny** [comment]
Hi!

Hopefully you are aware of the deprecation, but if not see
- #864 

For the image in question, we do not control the `godaddy` organisation on docker hub and it looks like they have removed the kuberentes-external-secrets repository.
The previous versions should have been mirrored to GHCR tho so you should be able to update your docker source to 
```
ghcr.io/external-secrets/kubernetes-external-secrets:6.0.0
```
alternatively you should be able to switch `godaddy` for `externalsecrets`
https://hub.docker.com/repository/docker/externalsecrets/kubernetes-external-secrets 
 to keep going :) I would highly recommend moving to a newer version (and away from KES)

**Comment by harsha448** [comment]
Hi Markus,
   Thanks for the reply..Im' able to pull image after updating my docker source
