### ISSUE TITLE
Inconsistent error handling for JSON secrets

### ISSUE THREAD

**Issue by Flydiverny** [external-secrets/kubernetes-external-secrets#97]
When using JSON formatted secrets and selecting properties in them the error handling seems inconsistent.

https://github.com/godaddy/kubernetes-external-secrets/blob/d04cf1de5e3793522f3d46a9b9be9f25413e5f15/lib/backends/kv-backend.js#L34-L41

If theres a parsing error its just swallowed with a warning log, while if the property doesn't exist it goes boom, shouldn't these be dealt with in the same way? Not being able to parse the secret seems worse to me than not finding the correct property, though they are probably equally big issues 😄

**Comment by silasbw** [comment]
I agree.  How about we `throw` on both of them and let the error bubble up to the [exception handler](https://github.com/godaddy/kubernetes-external-secrets/blob/master/lib/poller.js#L77)?  Separately we can decide on a better way to handle them (*e.g.*, add an annotation).

Thoughts?

**Comment by ecout** [comment]
Yes, bubbling up is a good approach.
